### ISSUE TITLE
in "invert" mode, images natively smaller than the viewport are placed and bounded badly

### ISSUE THREAD

**Issue by brobison75** [timmywil/jquery.panzoom#104]
Hello!  I've found an apparent bug in panzoom - images which are natively narrower or shorter than the viewport, get incorrect bounds and initial placement in "invert" mode.  Long story short, this in jquery.panzoom.js:

if (contain === 'invert') {
  diffW = width > container.width ? width - container.width : 0;
  diffH = height > container.height ? height - container.height : 0;

... should probably be:

if (contain === 'invert') {
  diffW = width - container.width;
  diffH = height - container.height;

I have a small test case at:

http://www.brobison.com/panzoom_invert_bug.tgz

You can see the problem and fix as follows:

1. extract panzoom_invert_bug.tgz in a web-server directory (creates directory "panzoom_invert_bug")

2. navigate to testcase.html; checkerboard image should be partially out of the viewport (too far left)

3. edit testcase.html to use jquery.panzoom-bugfix.js

4. refresh; image should now be placed correctly (width exactly covers viewport).

Please let me know if you disagree with the fix, or if you need more information.  I would submit a change directly, but I'm git-illiterate, and I'm hoping that this is a small-enough change that you won't mind taking care of it.

Thanks!

Brian

**Comment by fdev** [comment]
Was having this issue as well and the proposed fix works for me. Will this pull request be commited?
