### ISSUE TITLE
range slider broken in IE 11 (test for input-event support gives false positive)

### ISSUE THREAD

**Issue by brobison75** [timmywil/jquery.panzoom#106]
The range slider for (certain builds of) IE 11 is broken.  Go to:

http://jsfiddle.net/Ty2af/1/

... in an affected version of IE 11 (builds 11.0.9600.17105 and 11.0.9600.17107 are affected).  The slider appears, but dragging it has no effect.  It works in Chrome, Firefox, etc.

This is at line 85 of jquery.panzoom.js:

return typeof input.oninput === 'function';

Unfortunately, affected IE 11 builds return true but do not actually seem to support the 'input' event.  This replacement was suggested by user "Ginawa" on issue 90, to explicitly override for (some) known bad browsers:

return !!navigator.userAgent.match(/Trident\/7\./) ? false : typeof input.oninput === 'function';

I've confirmed this causes the slider to work again on 11.0.9600.17107, though I can't vouch for it being a perfect match.  To see this fix in action, change the external resource to:

http://www.brobison.com/pz2/jquery.panzoom-bugfix.js

Thanks!

**Comment by harpreet86** [comment]
Guys,

Facing the same issue. Need the fix on urgent basis. 

Do I need to follow the above mentioned change(http://www.brobison.com/pz2/jquery.panzoom-bugfix.js) as that works fine for me?

Any updates/suggestions?
