### ISSUE TITLE
Image rotation broken

### ISSUE THREAD

**Issue by mikaelho** [timmywil/jquery.panzoom#113]
If panzoom is used on an image (instead of a containing div) that contains information about the correct rotation (e.g. camera was held vertically and image should be displayed accordingly), this information is not respected and the image is displayed with the wrong rotation. Without panzoom, image is displayed with the correct rotation. 

Tested: Safari, iPhone 5s, iOS 7.1.2

**Comment by timmywil** [comment]
This has been fixed in master.
