### ISSUE TITLE
on.mousedown event blocked in latest IE 11 version

### ISSUE THREAD

**Issue by danilibros** [timmywil/jquery.panzoom#133]
Hello, 

Since a recent update to IE 11 (it seems to be the update on August 23, 2014, my current version of IE is 11.0.9600.17280), it appears mousedown events are no longer being fired when using panzoom. 

Here is a simple jsfiddle: http://jsfiddle.net/dlbooks/msL23s2q/7/

It looks like mousedown events for the div on which panzoom is initialized and any child divs are being blocked. These events fire correctly in FireFox and Chrome and IE 10, and they were working in IE 11 before the latest update. 

Do you have any suggestions for a workaround for this?

Thanks!

**Comment by aarontgrogg** [comment]
I know this is not an ideal solution, but I was able to resolve this by replacing:
`var str_start = pointerEvents ? 'pointerdown' + ns : ('touchstart' + ns + ' mousedown' + ns);`
with:
`var str_start = ('touchstart' + ns + ' mousedown' + ns);`

Cheers,
Atg

**Comment by payne8** [comment]
Is there any update to this or do I need to modify my copy of the plugin?

**Comment by MicheleBertoli** [comment]
+1

**Comment by pehbehbeh** [comment]
+1

**Comment by frankdenouter** [comment]
+1 (Also MS Edge in Win10 does not capture the mouse-down. The right-mouse-click however is captured a mousedown )

**Comment by jacobuid** [comment]
+1
