### ISSUE TITLE
Dragging issue for SVG in object tag with type as "image/svg+xml" instead of "image/xml"

### ISSUE THREAD

**Issue by nonintanon** [timmywil/jquery.panzoom#140]
From your demo here http://codepen.io/timmywil/pen/Fjfuy. I change the object type attribute to "image/svg+xml" and the dragging feature is gone. Not actually gone but your have to fine the move cursor somewhere in the edge.

I think "image/svg+xml" is the proper type for SVG image and I need to use JavaScript to access SVG element to change the color.

Do you think it is possible? Thanks for your great work!

**Comment by timmywil** [comment]
You just need the object to not eat all the pointer events. http://codepen.io/timmywil/pen/qNpykA
