### ISSUE TITLE
Panning and Zooming is very slow on Android

### ISSUE THREAD

**Issue by deznuios** [timmywil/jquery.panzoom#141]
First of all I would like to thank you for making such an awesome plugin. Its been really helpful for panning and zooming SVG.

I have been having some issues with my SVG file on Android devices. Whenever I try to use pinch gesture to zoom in or zoom out, or try to pan my SVG, it's very very slow. It works much better on iOS devices. I have also noticed that if I do not include the plugin, then zoom in, and zoom out is much more faster then when I include pan zoom library. I am not sure what am I done wrong, or if there is something wrong with my SVG file. I will really appreciate if you can provide me any pointers regarding same.

Following is the URL to see the SVG performance issue
http://salesarchitect-build.bhitest.com/sitemappreview?siteid=70&communityid=709&ios=1

I am using following code to setup pan and zoom to my SVG

 function setUpPanAndZoom() {
                var section = $('#canvas');
			    section.find('svg').panzoom({
                    increment: 0.3,
		            minScale: 1.0,
		            maxScale: 9.0,
		            rangeStep: 0.05
                });

                section.find('path').each(function () {
                    $(this).on('mousedown touchstart', function (e) {
                        e.stopImmediatePropagation();
                    });
                });
            }

**Comment by SamuelMichelRiad** [comment]
Hi @deznuios, did you ever find a solution to this performance issue?

Thanks
