### ISSUE TITLE
Centering image on zoom in/out

### ISSUE THREAD

**Issue by YOUR1** [timmywil/jquery.panzoom#148]
Whenever I zoom (wether its by buttons or by the slider) the image won't stay in the middle of the parent div, causing me to drag every time I zoom. Is there someway to fix this? 

Demo:  http://wiki.appnetwork.nl/test/

**Comment by julianxhokaxhiu** [comment]
+1 having the same issue. Any fix found?

**Comment by YOUR1** [comment]
Try adding "contain: false"

**Comment by julianxhokaxhiu** [comment]
Tryed and not working

**Comment by wowgl** [comment]
Did you ever find a solution for this?

**Comment by nikulchauhan** [comment]
I have same issue image does not zoom in and out from center of parent DIV. So If you have found any workaround for this then please answer here.

**Comment by davidtruchet** [comment]
Having the same issue on mobile when you are doing pinch/pull any workaround?

**Comment by nikulchauhan** [comment]
No still not get any workarounds for this.

**Comment by danleveille** [comment]
I'm trying to do this as well.

**Comment by timmywil** [comment]
transform-origin normally takes care of this if the image is already centered. If not, set the focal option manually to the center of the div...

http://jsbin.com/sojulof/edit?html,js,console,output

**Comment by nikulchauhan** [comment]
Thanks.
