### ISSUE TITLE
Panning issue in Firefox when scrolling used for div

### ISSUE THREAD

**Issue by jigarmodi-spec-india** [timmywil/jquery.panzoom#151]
Hi,
I have used Panzoom in one of my current projects for Zooming and Panning feature. So far it has worked very well. I have given oerflow:auto property to the div on which I am using Panzoom. Now when the width of the div increases, there is a scrollbar coming for the div. This scrolling is working fine in chrome, but same is having issue in Firefox. Instead of scrolling, whole div is panning. My Firefox version is 34.0.5.

I am attaching sample HTML file for further explaining my issue. This is just a demo html, but my original code is similar to this and both are giving same issue. This issue is coming in Firefox only.

![html](<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script src="../../Scripts/jquery-2.0.2.min.js"></script>
    <script src="../dist/jquery.panzoom.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#mainzoom").panzoom({
                $zoomIn: $("#zoom-in"),
                $zoomOut: $("#zoom-out"),
                $reset: $("#zoom-reset"),
                minScale: 0.2,
                disablePan: false,
                maxScale: 2,
                increment: 0.05
            });
        });
    </script>
</head>
<body>
    <div id="main1" style="width: 100%; height: 250px; float: left; overflow: hidden !important; position: relative;">
        <div id="mainzoom">
            <div id="main2" style="width:2000px;height:200px;overflow:auto;float:left; border:solid 1px black; visibility:visible!important">
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
                testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
            </div>
        </div>
    </div>
    <br /><br />
    <div style="text-align: center; margin-top: 50px;float:left;">
        <button id="zoom-in">Zoom In</button>
        <button id="zoom-out">Zoom Out</button>
        <button id="zoom-reset">Reset</button>
    </div>
</body>
</html>
)

![image](https://cloud.githubusercontent.com/assets/10306088/5557952/f91fbc1e-8d39-11e4-860d-a58f4c160c8d.png)

I am stuck in this issue and cannot find any solution for this. Please let me know if any further details required.

Thanks in advance.

**Comment by timmywil** [comment]
Expired.
