### ISSUE TITLE
HTML element - Select box in zoom area disabled

### ISSUE THREAD

**Issue by Mattajames** [timmywil/jquery.panzoom#156]
Hi Tim. Hope you can help, I have an HTML select box element that is not responding once in pan zoom mode. Is there a fix for this. I have tried different CSS pointer-events & z-index to no effect. Any advice would be much appreciated. Many thanks Matt

**Comment by timmywil** [comment]
Thanks for opening an issue.
This can be fixed by adding the following

```js
$('.panzoom select').on('mousedown touchstart pointerdown', function(e) {
  e.stopImmediatePropagation();
});
```

The event is not propagating to the document due to the panzoom handler.
