### ISSUE TITLE
predefined onClick events get erased

### ISSUE THREAD

**Issue by Davidx7** [timmywil/jquery.panzoom#158]
I have a complex SVG with lots of different onClick() functions defined from jquery, but when I enable this plugin for zoom and pan, they do not fire anymore, probably overwritten.

Any fix for that? 
There are also other plugins accessing the same target SVG so it's not possible to use only your plugin for everything

**Comment by timmywil** [comment]
Thanks for opening an issue. Panzoom does not remove other click handlers. However, it does stop propagation, which can prevent other handlers from running. If there is a specific element in your svg that needs to accept click handlers, you can fix it with the solution in question 2 of the FAQ.

https://github.com/timmywil/jquery.panzoom#faq
