### ISSUE TITLE
Zoompan stopping tap/click event propagation on swf

### ISSUE THREAD

**Issue by vinukumar-vs** [timmywil/jquery.panzoom#162]
I am using panzoom plugin for touchscreen. I loaded swf file in Object tag. when i tap/click, SWF has to access this click event to do some movie clip actions inside swf. But panzoom is stopping event propagation. How can i achive  this.

**Comment by timmywil** [comment]
Thanks for opening an issue. I think you can achieve this using `event.stopImmediatePropagation()`. See question 2 from the [faq](https://github.com/timmywil/jquery.panzoom#faq).

**Comment by vinukumar-vs** [comment]
Thanks for your quick reply. If i stop event propagation, i can't achieve pinch zoom and pan actions of swf/object. 
Presently pinch zoom and pan actions are working fine. Along with this i has to find which element has clicked in swf object when user TAPS. 
If i use event.stopImmediatePropagation(), zoom and pan actions are not working.
