### ISSUE TITLE
Keep transform on setmatrix

### ISSUE THREAD

**Issue by rushingfitness** [timmywil/jquery.panzoom#165]
Hey there, so first, I love this library. It's awesome, thank you so much.

So I built in a custom rotate button for my images which uses the transform css property. I was able to append new rotation degrees after the matrix attr. But once I move or zoom in, obviously the entire transform property is rewritten, including the rotate I added in.

How should I go about editing the js code in panzoom.js to keep any rotation already in the attr?

Thanks again so much!

**Comment by david-hollifield** [comment]
+1

**Comment by marieli** [comment]
+1

**Comment by SamuelMichelRiad** [comment]
+1

**Comment by rushingfitness** [comment]
Hey all. I ended up making it work on my site. I don't have the code in front of me on how I did it. But you can check it out on my site here as an example. When the page loads, just click on one of the drawings on the right (desktop, mobile doesn't work for whatever reason). 
When I get a hold of my code and how I did it I'll update this. Cheers

**Comment by david-hollifield** [comment]
@rushingfitness this would be great! I just pulled out the code to make these changes.

**Comment by rushingfitness** [comment]
Alright so I looked over my old code and turns out I'm not even using PanZoom anymore. I just built out my own custom version with jQuery UI Draggable, custom zooming with my own matrix setting (using a slider).

**Comment by SamuelMichelRiad** [comment]
Can you share your code?

**Comment by rushingfitness** [comment]
So I use BlueImp Gallery as the main portion, it has a draggable action that doesn't use the matrix attribute. That just changes the `top, left up, down` css attributes. Then when I zoom in/out or rotate, I just manually change the matrix via the jquery's `.css('transform` and pass in a modified matrix based on the rotation number plus 90, and the value of my custom slider (that's actually what I attached jQuery UI draggable on, not the image itself)

**Comment by rushingfitness** [comment]
So I just put this in a function and call it when the rotate button is clicked, or when the slider is being dragged:

    $elem = $(".slide[style*='translate(0px, 0px)'] img");
    var left = $("#imageRange").val();
    if ($elem.css('transform') != 'none') {
      var trans = $elem.attr('style').split(' ');
      if ($elem.attr('style').indexOf('matrix') > -1 && $elem.attr('style').indexOf('rotate') > -1) {
        var matrix = (trans[0] + ' matrix(' + left + ', ' + trans[2] + ' ' + trans[3] + ' ' + left + ', ' + trans[5] + ' ' + trans[6] + ' ' +  trans[7]);
        $elem.attr('style', matrix);
      } else if ($elem.attr('style').indexOf('matrix') > -1) {
        var matrix = (trans[0] + ' matrix(' + left + ', ' + trans[2] + ' ' + trans[3] + ' ' + left + ', ' + trans[5] + ' ' + trans[6]);
        $elem.attr('style', matrix);
      } else if ($elem.attr('style').indexOf('rotate') > -1) {
        var matrix = (trans[0] + ' matrix(' + left + ', 0, 0, ' + left + ', 0, 0) ' + $elem.attr('style').split('transform: ')[1]);
        $elem.attr('style', matrix);
      }
    } else {
      var matrix = ('transform: matrix(' + left + ', 0, 0, ' + left + ', 0, 0)');
      $elem.attr('style', matrix);
    }

**Comment by SamuelMichelRiad** [comment]
Great, thanks!
