### ISSUE TITLE
How to make spatial effect on different layers

### ISSUE THREAD

**Issue by neuthral** [timmywil/jquery.panzoom#168]
hello, im currently trying to make a space type map and wonder if i could make panning on different layers of an svg image to move at a different rate, say i have 3 layers and want the front layer to move at normal speed and back layer at slower.

**Comment by timmywil** [comment]
Hmm, sorry I don't think that's possible with panzoom. If the layers overlap, the top element with Panzoom initialized would eat up the events, which caters to a different use case. There may be some fidgeting you could do to make this work, but it sounds like it might be out of scope for panzoom.
