### ISSUE TITLE
Disable pan while not zooming

### ISSUE THREAD

**Issue by icedocemile** [timmywil/jquery.panzoom#172]
Hi all, 
And thank you for your fantastic plugin !
I'm looking to find a way to disable pan only while we are not zooming.

Is there a solution ?
Looking around panzoomzoom event and scale. Is setting panzoom.options.disablePan=false in this event function should do the stuff ?

Thanks
Renaud.

**Comment by icedocemile** [comment]
Done it ;)
var $panzoom = jQuery("#views_block_mobile img").panzoom({
      minScale: 1,
      disablePan: true
    });
    $panzoom.on("panzoomzoom", function(e, panzoom, scale, opts){
      e.stopImmediatePropagation();
      panzoom.options.disablePan = false;
      if(scale == 1) {
          panzoom.options.disablePan = true;
          panzoom.reset();
      }
    });

**Comment by paulbors** [comment]
+1

I wonder if this should not be one of the plugin options :)

**Comment by rahulchandrasekharan** [comment]
+1

Wonderful fix! Thanks a ton!
