### ISSUE TITLE
"panzoomstart" event not fired when zooming using trackpad or mouse wheel but works fine when panning

### ISSUE THREAD

**Issue by hassanzaheer123** [timmywil/jquery.panzoom#175]
"panzoomstart" event is not firing when zooming using trackpad or mouse wheel but works fine for panning. same is the case with "panzoomend" event...

Is there any workaround to this that I can meanwhile try?

Thanks!

**Comment by iFadey** [comment]
@hassanzaheer123 It's firing :)
