### ISSUE TITLE
does not work in wordpress

### ISSUE THREAD

**Issue by brody182** [timmywil/jquery.panzoom#177]
Seems to be having some js conflict in WordPress.. is anybody experiencing this?

**Comment by myrmecia** [comment]
Hi, i've spend hours now i found a solution, I also wanted to submit the idea to the developper of this amazing plugin but I'm new to github and don't know exactly how to send suggestions.

` $panzoom.parent().on('mousewheel.focal DOMMouseScroll.focal', function (e) {

            e.preventDefault();

            var delta = e.delta || e.originalEvent.wheelDelta || e.originalEvent.detail;`

that is the two line I have modified to accept DOMMouseScroll events..

Hope it will help you, and if devlopper read that hope he can be aware to my suggestion :)
