### ISSUE TITLE
pan to correct zoom by coords by zoom 1

### ISSUE THREAD

**Issue by DragorWW** [timmywil/jquery.panzoom#183]
how to pan to point x y coordinate (zoom 1) to zoom (1,5)

text sample:
$map
  .panzoom('zoom',1)
  .panzoom('pan',100 + $wrap.width()/2,100+ $wrap.height()/2) // center
  .panzoom('zoom',1.5) // incorrect zoom, center is change

**Comment by vishalmote** [comment]
I am looking for the same kind problems solution. have any one got the solution?

**Comment by timmywil** [comment]
Set the focal option http://jsbin.com/sojulof/1/edit?html,js,output

**Comment by vishalmote** [comment]
@timmywil , this is not vanswer what we are asking for. If I already zoomed on one location like highlighting "A" (P,Q) location which is centre of view area. Now I want to pan to "B"(M,N) location as centre of view area with the same zoom level.

**Comment by timmywil** [comment]
@vishalmote In that case, I might need an example. Here's something to start with...http://jsbin.com/mofeli/edit?html,js,output
