### ISSUE TITLE
Limit panning by some percentage

### ISSUE THREAD

**Issue by iFadey** [timmywil/jquery.panzoom#184]
Is there a way to limit panning maybe by 50% of the image. For example while panning the image, if 50% of image is out of screen/panning area, then stop panning in that direction.

Check this demo:
http://ariutta.github.io/svg-pan-zoom/demo/limit-pan.html

**Comment by newcurzon** [comment]
increment:0.5
minScale:1
maxScale:1.5

**Comment by juhotik** [comment]
This issue is about setting the min/max to panning, not to zooming.

**Comment by newcurzon** [comment]
there is no way to limit panning if we use a big scale of zooming, i suggest to limit scale of zooming than panning, but try to limit panning with customize function setMatrix, good luck!
