### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by rktjmp** [timmywil/jquery.panzoom#185]
I was trying to bind my own zoom in and out buttons as per the documentation:

```
// Zoom buttons/links collection (you can also bind these yourself - e.g. `$button.on("click", function( e ) { e.preventDefault(); $elem.panzoom("zoomIn"); });` )
```

Calling `$elem.panzoom("zoomIn")` didn't work, after poking around I think this should be

```
$(".zoom-in-button").on('click', function(event){
  event.preventDefault()
  // call zoom to zoom in
  $img.panzoom("zoom")})

$(".zoom-out-button").on('click', function(event){
  event.preventDefault()
  // call zoom with true to zoom out
  $img.panzoom("zoom", true)})
```

Its only a minor issue since the `$zoomIn` and `$zoomOut` initialisation options work fine, though it should be noted that you must provide both else neither get bound.

**Comment by miloszw** [comment]
Especially the latter observation about both `$zoomIn` and `$zoomOut` having to be bound is worth mentioning in the docs.

**Comment by timmywil** [comment]
Docs fixed.
