### ISSUE TITLE
Centering to bottom of container when zooming out with contain: 'invert'

### ISSUE THREAD

**Issue by wowgl** [timmywil/jquery.panzoom#187]
As the title states. When zooming out of and image and the image becomes smaller than the container the image "docks" to the bottom or to the right of the container instead of the center.

Does anyone know if this is intended, or have I been incompetent at implementing the library correctly.

Thanks in advance for any responses.

**Comment by franferdez** [comment]
I have the same problem i'm still trying to figere out how to fix it.
