### ISSUE TITLE
Panzoomend fix for android chrome

### ISSUE THREAD

**Issue by bodgybrothers** [timmywil/jquery.panzoom#188]
On android if you do a 

"on('panzoomend), function( e, panzoom, matrix, changed){
       if ( !changed ) {
		//do something
	  }
}

The 'changed' var will always be true after a zoom or pan. This is due to android adding a lot of decimals to the location matrix. To fix this we change the code starting on line 61 of panzoom.js:

function matrixEquals(first, second) {
		var i = first.length;
		while(--i) {
			if (Math.round(+first[i]) !== Math.round(+second[i])) {
				return false;
			}
		}
		return true;
	}

**Comment by alexvanstalkeR** [comment]
Thank you!
