### ISSUE TITLE
Not all styles removed when 'destroy' called.

### ISSUE THREAD

**Issue by louiswalch** [timmywil/jquery.panzoom#189]
When calling element.panzoom("destroy"), not all CSS added by panzoom is cleaned up. `
backface-visibility: hidden; transform-origin: 50% 50% 0px;` remains, which causes a display issue if you initiate zoom again on an element which you previously destroyed.

**Comment by newcurzon** [comment]
please try this, put panzoom("reset") before panzoom("destroy")
