### ISSUE TITLE
Contain: 'invert' not working properly.

### ISSUE THREAD

**Issue by louiswalch** [timmywil/jquery.panzoom#190]
Refer to example below. Using the contain: 'invert', works when you pan up/down, however there is blank space (orange) to the size of the left/right of the image.

Example:
http://beta.louiswalch.com/panzoom/

 You may need to reload page after image has loaded for panzoom to work correctly, this is just a rough mock up, I'm using a pre-loader in real life.

**Comment by l3iodeez** [comment]
You are seeing the background color of your container. This is because panzoom will zoom out to show you the entire height of the image, and because your div doesn't match the aspect ratio of your content you can see the orange background. You could either change the color to something that won't be visible, or put it inside a <div> that is sized to match your content's aspect ratio, thus eliminating the visible background.

**Comment by louiswalch** [comment]
The orange is just there to demonstrate the negative area.

The containing DIV is 100% of viewport width so that when zoomed out the image would be horizontally centered, but when zooming in it spans full viewport width. If I set containing div to be the same aspect ratio of the image, it would create a bunch of white space below the image at the zoomed out state.

Can you think of an alternative solution?

**Comment by l3iodeez** [comment]
Im not sure I'm understanding what you mean. What should it look like in the zoomed out state? You could use minScale: in the options to keep it from zooming out beyond the point where it reaches the sides.

**Comment by louiswalch** [comment]
I took your suggestion and gave the wrapping div element a set width/height to match that of the inside image.

- At the zoomed out state, the image should be exactly 1000px wide and centered on the viewport (works)
- Once zoomed, if you pan over to the left/right you should not see any orange to the sides of the image. This is outside/behind the wrapping div element. Image should stop panning once it hits the sides of viewport.

**Comment by louiswalch** [comment]
Hello, checking back on this. Does anyone know how I can get the image, once zoomed in, not to scroll to the left/right past the image. (E.g. once zoomed you should never see the orange). http://beta.louiswalch.com/panzoom/
