### ISSUE TITLE
Feature: Ability to delegate panzoom for dynamic elements

### ISSUE THREAD

**Issue by tmorehouse** [timmywil/jquery.panzoom#191]
If would be nice to be able to use a CSS class selector to specify what elements to panzoom, via delegation.

Sort of like `$('body').on('<panzoom event>','.selector', function(){ <handle zooming stuff> });`

where panzoom is the event name for touch start, click, etc, and .selector is the class applied to elements that are to have panzoom applied.

This would be great for dynamically added elements (like lightboxes, etc), without having to modify other libraries (or create custom event handlers)

If one could pass an option for element class selector and a parent selector to limit the scope, it would be possible to bind to the particular events that panzoom uses, and filter only the elements that have the .selector (i.e.. `.panzoom`) class limited to the parent element (i.e. `body` or `.lightbox`)..

**Comment by timmywil** [comment]
This is not viable because Panzoom needs to be attached to the element it's moving.
