### ISSUE TITLE
Sometimes not works with google map

### ISSUE THREAD

**Issue by semirturgay** [timmywil/jquery.panzoom#194]
Hi. 
First of all thanks for this great plugin.. 
I have a problem which occurs when  i add a svg element to google map as a layer then initialize panzoom on this svg, generally it works.. but sometimes although the panzoom is initialized on svg; it doesn't scale the svg and zoom doesn't work(especially on iphones and ipads => ios  8.3).

**Comment by sazarag** [comment]
I have the same issue. Do you know the solution to this problem?
