### ISSUE TITLE
Blur on scale

### ISSUE THREAD

**Issue by phunksta** [timmywil/jquery.panzoom#196]
When zooming beyond the point where 1 image pixel = 1 screen pixel, the CSS transform introduces blurring to give the over-zoomed image an 'anti-alias' effect.

I do not seem to be able to work out how to disable this

I understand that the standards are unofficial and support is browser specific, but would it be possible for panzoom to have a 'Do not blur' on zoom?

**Comment by hdavidzhu** [comment]
It seems from the other issues that this is a -webkit issue. Hopefully, it gets resolved soon!

**Comment by timmywil** [comment]
Will be fixed by #84
