### ISSUE TITLE
Implement panning only on right click

### ISSUE THREAD

**Issue by vaibhavsah** [timmywil/jquery.panzoom#197]
Hey I am using a div in which I am adding elements drag and drop. On clicking any element, the element becomes draggable as the drag event needs to be called. But I want to implement panning in case if the number of elements are more than the size of div. Instead of scrolling I need to implement the panning in such a case. 
So I want to implement panning only on right click. 

If there is any other idea, how can I implement panning with dragging also enabled, then please suggest.

**Comment by maelfrize** [comment]
:+1:

**Comment by miloszw** [comment]
Change [this line](https://github.com/timmywil/jquery.panzoom/blob/master/src/panzoom.js#L890) to
`!options.disablePan && e.which === 3) {`. And don't forget to `preventDefault` the `contextmenu` event.
