### ISSUE TITLE
What is the $elem in the documentation?

### ISSUE THREAD

**Issue by hdavidzhu** [timmywil/jquery.panzoom#199]
I can't seem to figure out if it stands for the jQuery object itself or the $panzoom instance that follows.

```
$treeDisplay = $("#tree-display");
$panzoom = $treeDisplay.panzoom();
```

Would `$elem` be `$treeDisplay` or would it be `$panzoom`?

**Comment by liamr91** [comment]
It would be $treeDisplay or you could simply replace $elem with "$("#tree-display");"
