### ISSUE TITLE
"restDimensions" not working with Inverted Containment

### ISSUE THREAD

**Issue by liamr91** [timmywil/jquery.panzoom#203]
When using a 'responsive' container or when just updating the dimensions of the container after initialisation, inverted contain then no longer works.

This can be seen on the demo page:
http://timmywil.github.io/jquery.panzoom/demo/#inverted-contain

If you start out at desktop , zoom in , shrink down the browser and then try to pan, you now see the white space around the inner element.

I have tried resting the zoom level on resize and also using rest dimensions to alert the parent of the change, but none of these calls seem to solve this issue.

Can anybody advise?

many thanks in advance,
Liam

**Comment by timmywil** [comment]
You spelled it wrong a couple times, so I'll point it out: it's `resetDimensions`. And that works for me.
