### ISSUE TITLE
Click actions not working on elements that are inside Panzoom ( in webkit mobile browsers only)

### ISSUE THREAD

**Issue by ramansharma89** [timmywil/jquery.panzoom#204]
Hi guys,

I'm using this plugin to pan and zoom few boxes and each box has a button which triggers a popup but it's not clickable in webkit mobile browsers. I'm stuck very badly so any help would be much appreciated.

Thanks,
Raman

**Comment by xicuzuey** [comment]
i'm having the same problem, is there any solution?

Thanks,
Xico

**Comment by timmywil** [comment]
Please see the second question of the FAQ in the README: https://github.com/timmywil/jquery.panzoom#faq

**Comment by xicuzuey** [comment]
Thanks timmy, it works fine.

**Comment by xicuzuey** [comment]
is there any way to make the page an automatic zoom depending on the size of the parent div?
I need it to adjust the content to a tablet or mobile phone or computer from a base size.

**Comment by timmywil** [comment]
There's not currently a way to automatically adjust the image size. I haven't had the time to implement this. For now, it should be doable outside the plugin with either css or some event handler in user code. Sorry for the inconvenience!

**Comment by xicuzuey** [comment]
Ok, no problem, thanks anyway.

**Comment by kkotkkio** [comment]
Thank you so so much
