### ISSUE TITLE
Determining the current centre coordinates of the image within a Viewport

### ISSUE THREAD

**Issue by iQuori** [timmywil/jquery.panzoom#206]
I am scaling/panning an image within a parent Div which has a fixed size.  It is working really well.  
One thing I want to is, at any given point in time, determine the x,y point of my image that is at the centre of the parent Div.
When the zoom factor = 1, then this is trivial.  It's just that when the zoom factor is not 1, I'm having a bit of trouble.
I am using the 'getMatrix' method and using the offsets [0], [4] and [5].  When [0] is != 1 (zoomed) I'm having issues determining what the relationship that [[4]] (x) and [[5]] (y) have to my calculation. 
Do you have any advice for me?  Is it possible to do what I am asking using the values from the matrix?
Thanks
Rob.

**Comment by diannall** [comment]
I'm having this problem too... jquery position (suggested in another issue) doesn't work consistently.
It would be great to get the current x,y taking scale into consideration.

**Comment by diannall** [comment]
I'm sure you've figured something out, but here is how I calculated the x,y - for anyone who comes across this and needs a hint. Super simple but my brain wasn't thinking of it.

```javascript
drag_width = 150;
x = matrix4 - ((drag_width * matrix1 - drag_width)/2);
y = matrix5 - ((drag_width * matrix1 - drag_width)/2);
```

(Wanted to avoid linking the matrix with the markdown syntax, so note that those are array indexes on the matrix array)
