### ISSUE TITLE
contain: 'invert' but snapping back into position?

### ISSUE THREAD

**Issue by philgyford** [timmywil/jquery.panzoom#210]
I want the general behaviour of `contain: 'invert'` but would like the image to "snap back" into position when the user tries to drag it. By default, the image will not move at all if the user tries to drag it outside of the container, which feels slightly "broken" - I'd like to let the user drag the image, but once they let go, it snaps back to its previous position.

I'm not sure if this is possible, or how complicated it would be... any thoughts?

**Comment by philgyford** [comment]
I've found that if I comment out [this line](https://github.com/timmywil/jquery.panzoom/blob/master/dist/jquery.panzoom.js#L574):

    marginW += (container.width - width) / 2;

then the image loads in the correct place, centred horizontally in the viewport. But then it can be dragged off the viewport, which is obviously not correct when contain is 'invert'.

**Comment by timmywil** [comment]
This is possible, but would require an animated pan in a panzoomend event.
