### ISSUE TITLE
Scrolling across pandzoom content

### ISSUE THREAD

**Issue by ShakurOo** [timmywil/jquery.panzoom#211]
Hello,

I would like scroll by swipping across the pandzoom content.

In my project the image has width: 100% of viewport, and when my Inch is on the pandzoom image, nothing appened, logic. But have you any tip for allow the scroll despite pandzoom ?

Example : When the image hasn't yet zoom ? when the image has zoom but the image is blocked by the limits of parent container ? When the scroll represent a certain percentage  from bottom to top ?

Than'ks you

**Comment by kiddailey** [comment]
I needed this behavior as well.  It would be nice if there was a flag "panOnlyWhenZoomed" that you could set.  In the meantime you can fake the functionality pretty easily by watching the touchstart and touchend events and setting the disablePan accordingly. I tested this on iOS devices and in a variety of the Chrome device emulators and it seems to work fine:

```javascript
// Assuming we're starting in a zoomed-out state
isZoomed = false;

// Watch touchstart and disable panning if we're not zoomed in
$panzoom.on('touchstart', function(e) {
	if (!isZoomed)
		$(".panzoom").panzoom("option", "disablePan", true);
});

// Renable panning after done touching
$panzoom.on('touchend', function(e) {
	$(".panzoom").panzoom("option", "disablePan", false);
});

// When panzoom is zoomed, set boolean flag if we're zoomed in
$panzoom.on('panzoomzoom', function(e, panzoom, scale, options) {
	// We use a delta calculation here because scales are not
	// always exactly precise.  Adjust delta value as needed.
	isZoomed = Math.abs(scale - options.minScale) > 0.0001;
});
```

**Comment by thomasfrobieter** [comment]
I agree. This function is very important, otherwise the lib is kinda useless .. especially on smaller touch devices.
It is not a very special case, that an image has 100% width on those devices and i think every end user will leave the page in case of being captured inside this image pan container :\
