### ISSUE TITLE
Default size not exceeding container, but allowing zooming in and out

### ISSUE THREAD

**Issue by furzewolf** [timmywil/jquery.panzoom#214]
Is it possible to set the default size of the display so that the image fits the container in width or height, but still allows zooming in and out?

When I use this with an image, I have to zoom out to see the whole thing. What would be useful is if it could allow me to start the image fitting the container, and then let me zoom in or out if needed.

Thanks!

**Comment by kiddailey** [comment]
Definitely.  When your image loads, get the naturalWidth and naturalHeight, then get the width and height of the container.  Simple math will give you the percentage difference between the width or height to use for your initial scale.  Then use that percentage for the startTransform option on init.

You'll probably also want to calculate a minScale and maxScale using your calculated scale as a baseline and set those as well.

**Comment by giuseppepaul** [comment]
Kiddailey's method will work fine, and I've used it on a project I'm working on, but if it's just a simple setup you can actually achieve this with just css... 

.container { display:block; width:200px; height:200px; }
.container img { display:block; max-width:100%; height:auto; }

The zooming will be applied via css transforms and wont be affected by the max width.

**Comment by furzewolf** [comment]
@giuseppepaul That actually works perfect, thanks! It also fits in with my use of Flexbox, allowing me to center align it as well. I used the following:

.panzoom {
display: flex;
align-items: center;
justify-content: center;
height: 100%; // To make it fit in the parent
}
.panzoom img {
display: block;
max-width: 100%;
height: auto;
}

**Comment by furzewolf** [comment]
@kiddailey @giuseppepaul Any more ideas about how to get that to work? The other solution works, but I can't figure out how to centre align it. It's aligned to the left (and the top, if the image is small enough) and I'd ideally like it in the centre. Hope I'm not asking too much, just wondering if you have any pointers!
