### ISSUE TITLE
Html links not clickable on mobile browser

### ISSUE THREAD

**Issue by wagnerpaz** [timmywil/jquery.panzoom#216]
I'm trying to apply zoom to html content but on mobile browser the links are not clickable. Maybe it's something related to touch events?

**Comment by timmywil** [comment]
Thanks for opening an issue. Event delegation is disabled in panzoom elements by default. If something needs to be clickable, add a click/touchend handler to the clickable elements that calls `event.stopImmediatePropagation()`. See the 2nd question in the [FAQ](https://github.com/timmywil/jquery.panzoom#faq).
