### ISSUE TITLE
Set initial zoom to zero?

### ISSUE THREAD

**Issue by laneystroup** [timmywil/jquery.panzoom#218]
Is there a way to set the initial zoom to zero? It always starts around 110% zoom, and I am not sure how to alter that.

Thanks,
Laney

**Comment by dbnoble** [comment]
@laneystroup just call the zoom function immediately after initializing as shown in the documentation.

$elem.panzoom("zoom", 1.0, { silent: true });

**Comment by laneystroup** [comment]
OK, thanks. It seems like there should be a way to set the initial zoom without having to adjust it after the fact, but I will try this and see if it works.

**Comment by kiddailey** [comment]
Can you use the "startTransform" property?

```javascript
$(".panzoom").panzoom({
	startTransform: 'scale(1.0)',
});
```

You may need to also accommodate for the difference between your item and your container element's widths and heights.

**Comment by laneystroup** [comment]
OK, I figured this out. startTransform is the correct property to use for setting the initial zoom. I had tried this, but was confused because I had copied the code from the demo page, which uses both the startTransform as well as the silent zoom method (suggested by dnoble) after initiating. Therefore, setting startTransform to scale(1.0) was still resulting in a scale of 1.1 due to the panzoom("zoom") appended to the end.

Unless you are trying to animate the initial zoom or something, it seems like the least redundant way to do this would be to set the startZoom to "scale(1.2)" and remove the appended panzoom("zoom").

For reference, here is what is shown on the demo page for Inverted Containment:

        (function() {
          var $section = $('#inverted-contain');
          $section.find('.panzoom').panzoom({
            $zoomIn: $section.find(".zoom-in"),
            $zoomOut: $section.find(".zoom-out"),
            $zoomRange: $section.find(".zoom-range"),
            $reset: $section.find(".reset"),
            startTransform: 'scale(1.1)',
            increment: 0.1,
            minScale: 1,
            contain: 'invert'
          }).panzoom('zoom');
        })();

And here is the simplified equivalent without the additional panzoom("zoom") (just tested this on Safari 9.0.1):

        (function() {
          var $section = $('#inverted-contain');
          $section.find('.panzoom').panzoom({
            $zoomIn: $section.find(".zoom-in"),
            $zoomOut: $section.find(".zoom-out"),
            $zoomRange: $section.find(".zoom-range"),
            $reset: $section.find(".reset"),
            startTransform: 'scale(1.2)',
            increment: 0.1,
            minScale: 1,
            contain: 'invert'
          })
        })();
