### ISSUE TITLE
Pan to cursor

### ISSUE THREAD

**Issue by mikeeevillegas** [timmywil/jquery.panzoom#220]
Can you pan the image to the coordinates of the cursor after clicking? How?

**Comment by kiddailey** [comment]
At the very basic, wouldn't using the "pan" method triggered onClick do the trick for you? See:

https://github.com/timmywil/jquery.panzoom#pan-x-y-options-

Of course, you'd probably need to make sure you're not introducing a conflict with the click binding, but I think this could work.  You may also be able to use relative panning instead depending on how you have to calculate the X and Y deltas.

```javascript
$("#panzoom").bind('click', function() {

	// Calculate the offsets for the click position vs the position of elements
	var newX = currentMouseX ...
	var newY = currentMouseY ...

	$panzoom.panzoom("pan", newX, newY, { relative: false });

});
```

**Comment by mikeeevillegas** [comment]
this will do thank you :)
