### ISSUE TITLE
Question: Issue movements to another instance

### ISSUE THREAD

**Issue by Risingson** [timmywil/jquery.panzoom#221]
Hi, i am unsure how to use the right words but trying to explain my question as follows:

I got 2 elements (divs) with different panzoom options like
$panzoom=$("#viewport").panzoom(...
$bgpanzoom=$("#background").panzoom(...

$panzoom covers the whole screeen and $bgpanzoom is positioned underneath (z-index) it.

Now what i would like to achieve is that $bgpanzoom gets panned aswell when $panzoom gets panned. The idea behind it is trying to achieve a parallax effect where the $bgpanzoom moves with different options (smaller increment) than the $panzoom content.

So when i pan on screen using the mouse both instances should move with their individual options...

I hope i managed to outline the question :)

Thank you for your project and for your help
Thomas

**Comment by kiddailey** [comment]
I answered a question that is somewhat related to this the other day that might get you part of the way.  The request was basically to be able to pan to the current mouse cursor position.

Using that idea, you could tie into the panzoomchange event on the topmost panzoom and then issue a pan() call to the lower panzoom object passing in the matrix provided by the panzoomchange.  I've not tried it, but I would imagine it's possible.

Check out: "Pan to cursor" Issue # https://github.com/timmywil/jquery.panzoom/issues/220 to see my reply on that thread.

**Comment by Risingson** [comment]
hi, thanks for your reply. my problem is that i want the lower panzzom to act like it was panned with its own options. the movement of the topmost panzoom is only relative to the background panzoom. i am sure i could calculate the relative pan coordinates but thats not why i chose a plugin in the first place :)

**Comment by timmywil** [comment]
See the `$set` option. If that doesn't help, please reply here.
