### ISSUE TITLE
How do I record image size and position after scaled?

### ISSUE THREAD

**Issue by neilliang** [timmywil/jquery.panzoom#224]
This is a really amazing stuff for resizing/moving object on mobile. I am trying to use it on setting user's portrait, but I found it uses css matrix to control photo size and position. It there a best way to record and apply photo information after users finish their operation? Thank you.

Sorry about my English.

Paul

**Comment by SeanHayes** [comment]
$el.panzoom('getMatrix')

Returns matrix.

http://www.w3schools.com/css/css3_2dtransforms.asp

Tells you what the matrix values do. 1st and 4th element give x/y scaling, 5th and 6th give x/y offset.
