### ISSUE TITLE
Contain: hides image on mobile

### ISSUE THREAD

**Issue by mariothegreat** [timmywil/jquery.panzoom#226]
Hello I am having the following problem  that appears to happen only on mobile resulting in displaying my image on partially . I am using this

`  var $panzoom = element.panzoom({
                minScale: 1,
                maxScale: element.naturalWidth / element.clientWidth,
                contain: 'invert'
            });` 

in order to keep my image contained in its parent. Even though it works perfectly fine on desktop computers it does not work as expected on mobile devices. It wont let me pan through the whole image and as a result it will display just a percentage of the image. However, if i zoom in the image it will let me pan further down the image. **It is important to emphasise that this happens only on mobile and not with all images. The image that seems to have a problem is an infographic which is long in height.**

**Comment by timmywil** [comment]
Would need a working example to help debug this.
