### ISSUE TITLE
Set contain to limit on grandparent, rather than direct parent.

### ISSUE THREAD

**Issue by ChrisJaquezOS** [timmywil/jquery.panzoom#230]
Hello! I have some panzoom images inside a div which is inside a wrapper. How do I set it so contain blocks the image from moving outside the grandparent, rather restricting it inside the parent?

example markup:
Goal: contain panzoom within wrap, rather than parent
````
 <div class='wrap'>
   <div class='parent'>
       <img class='panzoom' src='..'>  
   </div>
 </div>
````

**Comment by timmywil** [comment]
You can do this by overriding `$parent` on the panzoom instance...

```js
var instance = $elem.panzoom('instance');
instance.$parent = $('.wrap');
instance.resetDimensions();
```

It will then use wrap's position/dimensions for the container.
