### ISSUE TITLE
Making the panzoom element zoom outside of its parent

### ISSUE THREAD

**Issue by Moghul** [timmywil/jquery.panzoom#231]
I was having an issue with centering the popped out element at the center of the screen. The available methods online included changing the position to absolute (which completely broke the zoom) or using a margin-top value (which made the image zoom far below the point in between the fingers).

I went for a different solution where I created a div container for the panzoomed image and the container itself was centered on the screen. This worked well with contain-invert, except the image would not zoom in such a manner that it would be able to zoom to more than the size of its parent (it would zoom but stay in the confines of its parent. Even if I set the container size to 1px by 1px so it is definitely smaller than the panzoomed element, it did not behave as expected).

The issue, I found, was that the container, at runtime, was assigned a style of "overflow:hidden". I fixed my issue by changing line 886 in jquery.panzoom.js to overflow:'visible'.

I am unsure whether the initial behaviour was intended but that particular line will change it to what I want it to do.

However, the creator should consider that developers might want their zoomable object in the center of the screen (by that I mean the initial position) and note that it is unclear to me how to do this from the documentation (if there is a way).

**Comment by timmywil** [comment]
See http://jsbin.com/fiqeko/1/edit?html,js,output and its use of the focal option.
