### ISSUE TITLE
Vertical panning only

### ISSUE THREAD

**Issue by quocanh176** [timmywil/jquery.panzoom#235]
Hi timmywil,
is there anyway that u could restrict the panning only vertically ? I have a table which  only its width is bigger than container. So i just want to pan it left-right. 
And it is possible to set that it could only pan until it reach the border(left/right) of the table? 

Thanks for the amazing work!

**Comment by grapho** [comment]
I seem to have a bug that only allows me to pan vertically

**Comment by timmywil** [comment]
See the recently added `disableXAxis` option.
