### ISSUE TITLE
Any way to center Panzoom when clicking reset?

### ISSUE THREAD

**Issue by davidmandeeli** [timmywil/jquery.panzoom#236]
Here's a sample I've done.
http://jsfiddle.net/Khvrj/445/

If the whole container thing is larger than the browser size and when clicking on the button reset. It goes on to the Top Left side of the container,

How do I keep it Top Centered?

**Comment by danleveille** [comment]
@davidmandeeli Any luck with this? I'm trying to center too but I'm having no luck.

**Comment by andreszs** [comment]
It would be nice to start with the image centered on the container, when it's smaller than its container.

**Comment by timmywil** [comment]
I think this can be accomplished by setting the `startTransform` option to an appropriate center position.
