### ISSUE TITLE
Panning on mobile (Nokia Lumia 520)

### ISSUE THREAD

**Issue by wandrer92** [timmywil/jquery.panzoom#238]
When panning a zoomed element (only tested on Nokia Lumia, Windows 8.1, IE11) the window scrolls with the in the direction of the drag, even with no overflow. 
Right and left window drags trigger 'back' and 'forward' history actions by default so this is an unwanted behaviour when trying to drag a div.
I tried adding 'touch-action:none' to html and body on 'panzoomstart' and removing on 'panzoomend' but this is a weak solution as the scrolling registers before the event seems triggers.
Any thoughts?

**Comment by timmywil** [comment]
I'm not sure. I'd need a test case to investigate further.
