### ISSUE TITLE
Image getting flushed to the right side of the <section> tag

### ISSUE THREAD

**Issue by Sue-k** [timmywil/jquery.panzoom#241]
Hi,

The image is getting flushed to the right side of the <section> tag leaving quite some space at left, top & bottom. In other words, image is not aligned centrally inside the <section> tag. I tried float or padding but with this part of the image is not visible when zooming. Any suggestions on how I can align the image centrally within the <section> tag? 

Here is the code:

    <section>
      <div class="buttons">
		<button class="zoom-in">+</button>
		<button class="zoom-out">-</button>
		<button class="reset">Reset</button>
      </div>
      <div class="parent">
        <div class="panzoom">
		  <img src="http://www.site.com/car.jpg" class="zoomimage">
        </div>
      </div>
      <script>
        (function() {
          var $section = $('section').first();
          $section.find('.panzoom').panzoom({
            $zoomIn: $section.find(".zoom-in"),
            $zoomOut: $section.find(".zoom-out"),
            $zoomRange: $section.find(".zoom-range"),
            $reset: $section.find(".reset"),
            startTransform: 'scale(0.6)',
			minScale: 0.9,
            increment: 0.1,
            contain: "invert"
          });
        })();
	  </script>
    </section>

**Comment by timmywil** [comment]
I think this can be accomplished by setting an appropriate center value to the `startTransform` option. It will always reset to that transform.
