### ISSUE TITLE
panning not working on svg object

### ISSUE THREAD

**Issue by uchihamadara** [timmywil/jquery.panzoom#243]
Hello! Great lib!

I have a problem with the pan on an svg object. 

This is the inserction of the SVG Note: I want the lib to work only with svgs..

```
<div class="panzoom">
<?php
    if(str_to_lower($recinto->getTipo())=='svg') {
?>
<object id="recintosvg" style="opacity: 0" data="<?php echo $recinto->getRutaMapa(); ?>" type="image/svg+xml">
</object>
<?php
   }else{?>
        <img id="recintoimg" src="<?php echo $recinto->getRutaMapa(); ?>" class="img-responsive"/>
<?php
}
?>
</div>
```

Then in the js I have:

`
 $(".panzoom").panzoom({
                $zoomIn: $(".zoom-in"),
                $zoomOut: $(".zoom-out"),
                $zoomRange: $(".zoom-range"),
                $reset: $(".reset")
            });
`

The zoom works perfect, but I cannot pan at all...

Thanks in advance!

**Comment by timmywil** [comment]
Object tags can eat up the events. See http://codepen.io/timmywil/pen/qNpykA
