### ISSUE TITLE
get mouse click coordinates after a pan+focal zoom

### ISSUE THREAD

**Issue by bomastudio** [timmywil/jquery.panzoom#244]
1.  Before use jquery.panzoom:
I move a <div> from its original location to the actual mouse position:

$("#mydiv").offset({top: mouseY, left: mouseX})

Everythings goes ok

2. I use PAN
Same as 1.

3. I use FOCAL ZOOM
Strange behaviour....the div is located in the center of its parent DIV..... why?

**Comment by timmywil** [comment]
Keep in min the focal point is relative to the parent. See the [demo](http://timmywil.github.io/jquery.panzoom/demo/#focal) for an example.
