### ISSUE TITLE
Cannot pinch or zoom on mobile

### ISSUE THREAD

**Issue by StateBarofArizona** [timmywil/jquery.panzoom#245]
I've tried every possible setting and this works fine with a mouse wheel but ignores zooming via pinch on mobile.

`    <section id="focal">
        <h1>Use the mousewheel to zoom on a focal point</h1>
        <div class="parent">
            <div class="panzoom">
                <img src="/images/ConventionMapRevisedV6.svg" width="900" height="900">
            </div>
        </div>
        <script>
        (function() {
          var $section = $('#focal');
          var $panzoom = $section.find('.panzoom').panzoom();
          $panzoom.parent().on('mousewheel.focal touchstart', function( e ) {
            e.preventDefault();
            var delta = e.delta || e.originalEvent.wheelDelta;
            var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
            $panzoom.panzoom('zoom', zoomOut, {
              increment: 0.1,
              animate: false,
              focal: e
            });
          });
        })();
        </script>
    </section>`

**Comment by StateBarofArizona** [comment]
I found the cause, now what do I do?  This tag is blocking the ability to zoom on mobile but without it, the web page does not scale correctly, appearing too small.

`<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1, maximum-scale=2, user-scalable=yes" />`

**Comment by timmywil** [comment]
You should be able to remove the min/max scale options and keep the content width option.
