### ISSUE TITLE
Set CSS-class to HTML-element depending on zoom factor

### ISSUE THREAD

**Issue by joergsteinhauer** [timmywil/jquery.panzoom#247]
Hello, 

is it possible in an easy way to add e.g. a CSS-class to an HTML-Element depending on zoom factor?

For example if I zoom one Step, a div-element get a class `zoomed-1` etc.

I noticed, that the inline CSS value `martix` of transform-property (`transform: matrix(...)`) is affected by zooming. So maybe it is possible to go that way? Or is there an elegant way to do this?

Thanks

**Comment by timmywil** [comment]
You can bind to the `panzoomzoom` event and add classes based on the current zoom level. Hope that helps.
