### ISSUE TITLE
Set initial zoom to show entire image

### ISSUE THREAD

**Issue by andreszs** [timmywil/jquery.panzoom#248]
Hi, I use the plugin with the `contain:invert` mode in order to show the image in fullscreen.

But how can I configure the plugin so the initial zoom will **show the entire image** automatically instead of an arbitrary zoom value? That is, completely zoomed out if you want to call it that way.

Thank you, the plugin is great BTW.

**Comment by timmywil** [comment]
Sorry, I'm not sure what you're after. If you start with an example from jsbin.com or codepen.io, we can work through it.

**Comment by laziaf** [comment]
Same problem here with contain:automatic. when initialize image automatically zoom in, you can check on this plugin demo at section "Automatically determine the best containment option based on the panzoom element's relation to the parent", How can i show full image full screen when initialize, thank you
