### ISSUE TITLE
Doesn't work at all in jquery 3

### ISSUE THREAD

**Issue by Krillko** [timmywil/jquery.panzoom#249]
`$.event.mouseHooks` is deprecated in 3.0

**Comment by dirko0816** [comment]
Hi
I love your script but it's not working under jQuery 3.0
Is there any progress on this?

Dirk

**Comment by timmywil** [comment]
Sorry! I need to make time for it.

**Comment by timmywil** [comment]
Fixed by 5544d70e6ffada97b865c03f13492cb89e163637
