### ISSUE TITLE
Events not firing on setMatrix?

### ISSUE THREAD

**Issue by no3rdw** [timmywil/jquery.panzoom#250]
I have a panzoom instance set up with links outside which, when clicked, will pan/zoom the area to specified coordinates.  The panzoom instance can also be used normally, by click/dragging.

If you click and drag the panzoom area, the _panzoomstart_ event is fired, followed by the _panzoomchange_ and _panzoompan_ events (over and over until the drag is finished) and then finally the _panzoomend_ event.

When you click on my links outside the panzoom area, I call _setMatrix_ to have the panzoom instance transition to the specified location and zoom level.  animate:true and silent:false are set on this call to _setMatrix_.  When this is called, _panzoomchange_ is fired one time, before the start of the transition event.  As far as I can tell, there's no way to have an event occur during the transition or when the transition is complete when manually calling _setMatrix_.  

Is this intended?  Should I be using another method instead?

**Comment by timmywil** [comment]
Yes, since it is using a CSS transition. I think what you're looking for is https://developer.mozilla.org/en-US/docs/Web/Events/transitionend.
