### ISSUE TITLE
svg animation help

### ISSUE THREAD

**Issue by Risingson** [timmywil/jquery.panzoom#252]
### Subject of the issue
"...but one could implement transitions manually by overriding the setTransform() method and integrating a tweening library for javascript animations (such as tween.js)."

Is there an example for this somewhere? i would like to do this but i am no pro :)
thank you for the wonderful library !

### Your environment
* version of jquery.panzoom: 3.1.0
* version of jquery: 3.1.0
* which browser: webkit ios 9

**Comment by Risingson** [comment]
Since i don't need to support IE i ended up using version 2.0.1 for now and will try to mod 3.1.1 so it works with transitioning svg like 2.0.1.

**Comment by timmywil** [comment]
I'd like to construct an example that will work everywhere.

**Comment by timmywil** [comment]
Actually, I'm working on making SVG animations work with CSS wherever possible while still supporting IE9. Animations won't work there, but it's probably better than importing another library.

**Comment by Risingson** [comment]
Great news ! Looking forward to it and a big thank you !

**Comment by timmywil** [comment]
I had forgotten that it wasn't limited to IE9. The problem persists in IE10, 11, and Edge. That said, SVG transitions should work now in other browsers.
