### ISSUE TITLE
Drag image with touch device stopped working 

### ISSUE THREAD

**Issue by shlomiah** [timmywil/jquery.panzoom#253]
### Update jquery.panzoom version cause problems
I tried to update the jquery.panzoom and tilt (move) with touch stopped working, I assume it because the fixes in "Remove pointertouch; support jQuery 3.0".

### Environment
* version of jquery.panzoom : Release v2.0.6
* version of jquery: v2.0.3
* which browser and its version: Chrome Version 51.0.2704.103 m

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template]
example that it worked in v2.0.6: http://jsbin.com/yekititixi/edit?html,js,output
your example not works: http://jsbin.com/mofeli/edit?html,js,output.

### Expected behaviour
when dragging the image with touch it will move like dragging it with mouse

### Actual behaviour
Image is not draggable via touch

* I test it with touch screen and not tablet....

**Comment by timmywil** [comment]
Thanks for opening this issue! It has been fixed and a new version is in the process of release.
