### ISSUE TITLE
Minimum zoom to fill

### ISSUE THREAD

**Issue by ygoe** [timmywil/jquery.panzoom#255]
I have a container element that fills a fixed part of the page. The page cannot be scrolled. Within the container, there's a div element of a known size that should be scaled to fit inside the container of dynamic size (depending on the browser window size). The inner div should be as large as possible while still being completely visible initially (and centred) and the user must not be allowed to zoom out any more than that. The user must be able to zoom in though, to see the inner element larger.

What initialisation code should I use for that?

I've started with the basic example but find no option to set to achieve my desired behaviour.

* version of jquery.panzoom = 3.1.1
* version of jquery = 2.2.3
* which browser and its version = Firefox 47 on Windows 7

**Comment by timmywil** [comment]
You may have to calculate the starting size manually (based off the size of the container), but once you figure out the appropriate minimum scale, it can be set using the `minScale` option.

http://jsbin.com/vuzebe/edit?html,js,output

**Comment by ygoe** [comment]
I tried it with this code, but it produces strange behaviour. The panning is restricted to undefined borders somewhere outside and inside the actual edge of the containing element.

		var roomWrapper = $("#room-wrapper");
		var minScaleX = roomWrapper.innerWidth() / @project.RoomWidth;
		var minScaleY = roomWrapper.innerHeight() / @project.RoomHeight;
		var panzoom = $('#room').panzoom({
			minScale: Math.min(minScaleX, minScaleY),
			contain: "invert"
		});

I don't understand the 'contain' parameter. What are its allowed values and what will they do?

**Comment by timmywil** [comment]
There are 3 `contain` values in the latest version: `true`, `"invert"`, and `"automatic"`. The [demo](http://timmywil.github.io/jquery.panzoom/demo/#contain) has examples of the different contain options, but here's a rundown.

- `true`: The image is expected to be smaller than the container. The image is restricted to its container.
- `"invert"`: The image is expected to be larger than the container. The image is restricted to outside its container. In other words, if the container had a background, you shouldn't see that background, only the image.
- `"automatic"`: The contain value is determined automatically based on the image size, and the contain value for the x axis can differ from the y axis. If the image is smaller than the container, contain is set to `true`; if larger, contain is set to `"invert"`.

It sounds like maybe you want `contain: "invert"`, but set along with a ```startTransform: `scale(${minScale})` ```.

**Comment by ygoe** [comment]
`"invert"` wouldn't work because if the aspect ratio of the container doesn't match the aspect ratio of the content, some content would be clipped. What I need is this:

* The content must fit the container and never be smaller
* The content must be centered in the container if there's some space around it
* The content may be zoomed in but never be dragged inside the container too far

This is really hard to explain. I think I'll best show you with some examples:

![panzoom-examples](https://cloud.githubusercontent.com/assets/868315/17132756/6ce8c39c-5323-11e6-9748-33d9f40c87e2.png)

The documentation shows `content: false` as default. What does that mean? I guess it means "no restriction at all" as opposed to all of the three options you explained now.

**Comment by ygoe** [comment]
Oh, and when I set `contain: true`, my content is offset to the top and left and can never be seen completely while there is still plenty of empty space on the bottom and right side. There's some offset confusion in panzoom I guess.

**Comment by shlomiah** [comment]
:+1: 
Wow! You describe exactly the bugs I had!
I solved 2 out of the 3:
For image 3: 'NOK: too small' - I just set minScale: 1, and my image stays height: 100% of the parent.
For image 6: still not resolved :(
For image 2: I wrote some code that resolves it (but the code is not 100% perfect), I hope it can help you too:

1. at the end of the zoom function add:
`if (this._isImageSmallerThanParent()) {
				this.resetPan();
			}`

2. add this method:
`_isImageSmallerThanParent: function () {
			var currentScale = this._getCurrentScale(),
				imageWidth = currentScale * this.$elem.width(),
				containerWidth = this.$parent.width();
			return imageWidth < containerWidth;
},`

3. add this method:	
`_getCurrentScale: function () {
	var matrix = this.getMatrix();
	return Number(matrix[0]);
},`

4. add in _startMove function the code:
`if (self._isImageSmallerThanParent()) return;`
I put that code just before:
`// Set pan
					self.pan(
						+matrix[4] + middle.clientX - startMiddle.clientX,
						+matrix[5] + middle.clientY - startMiddle.clientY,
						panOptions
					);
					startMiddle = middle;`

5.  add in the same function (_startMove ) the code:
`if (self._isImageSmallerThanParent()) return;`
but this time in the move = function (e),  right after the e.preventDefault();

**Comment by shlomiah** [comment]
And last thing ... 
I'm using contain: 'invert'

**Comment by ygoe** [comment]
@shlomiah Where did you put your code? Did you modify this library?

I feel the need to add two more samples to make certain edge cases clearer. Here's the updated demo image:

![panzoom-examples](https://cloud.githubusercontent.com/assets/868315/17135121/60b66614-532e-11e6-93da-499507b00373.png)

Resizing the container should also be handled so that the shown restrictions are obeyed at all times. In my case the content has always a fixed size though which cannot be changed during the page's lifetime. I guess that means that minScale would have to be recomputed every time the container's size changes. The panning offset must then also be checked and updated. I can't do any of this as long as panning behaves randomly, pushing my content out of view somewhere. In which reference is the panning offset evaluated: The original size or the scaled output size on the screen?

I'd compare the described requirements with the standard behaviour of any image viewer that you may find on your smartphone or tablet. Images start out completely visible, zoomed to fit and centered. You can then zoom in but the inside egde of the image will never cross the outside edge of the container unless its extent is too small, in which case that dimension will be centered.

**Comment by shlomiah** [comment]
I changed my local file "dist/jquery.panzoom.js" that I'm using,
I didn't try to insert the code to github because I use v2.0.5.
I tried to update my version to the latest (v.3.1.1) but it was too bugy.
* my fix is also support touch.

**Comment by ygoe** [comment]
I found a partial solution and added the remaining issue as #258.

**Comment by ygoe** [comment]
No, my solution only works if the content is smaller than the container and minScale is > 1.

If the content is larger than the container and minScale is < 1, the content will be too small. There's empty space in both dimensions. Somehow I believe that the scaling mechanics in this library are fundamentally wrong. Which would mean I can't use this and probably need to write it myself somehow.
