### ISSUE TITLE
Initial Zoom and Focus

### ISSUE THREAD

**Issue by daudirsch** [timmywil/jquery.panzoom#256]
I've seen questions on this before but none seem to resolve my issue and it maybe a misunderstanding by me.  Like many, we're using your awesome plugin to allow users to pick and crop a profile pic.  I'm trying to set the initial zoom so they can see the entire image on load.  I'm using the startTransform and it's working but I can't get the image to load in the top, left corner.

Here's a codepen to demonstrate what's happening:  http://codepen.io/daudirsch/pen/OXkoEq?editors=1010

Thanks in advance.

**Comment by timmywil** [comment]
The `focal` option should only be passed to the `zoom` method. I updated the example...

http://codepen.io/timmywil/pen/grzqRO?editors=1010

I set the focal point to `8, 8` because of the body margin.
