### ISSUE TITLE
Exponential zoom is too quick

### ISSUE THREAD

**Issue by ygoe** [timmywil/jquery.panzoom#257]
I've seen that exponential zoom was added in a current release. While I understand its difference and also find that linear zooming is too "slow", the current implementation feels too quick, especially in higher zoom levels. I also have the impression that the increment option is ignored when exponential is enabled.

**Comment by timmywil** [comment]
I think I agree, but I haven't figured out a better algorithm yet. I'll work on this.

**Comment by ygoe** [comment]
You're using a square curve now. What looks nice in classic map interfaces (Google Maps has switched to smaller steps some time ago but OSM and Bing still use it) may be a bit too much for smaller worlds like mine. Maybe instead of x^2 the curve could go something like x^1.5. That exponent might even be adjustable. I don't know the level of math support in JavaScript required for this.
