### ISSUE TITLE
contain: "invert" moves content to bottom/right corner

### ISSUE THREAD

**Issue by ygoe** [timmywil/jquery.panzoom#258]
I figured out how to position the content inside the container to be centered initially (using [flexbox alignment](https://css-tricks.com/centering-css-complete-guide/), last sample there), and I can calculate and set minScale so that the content should always be scaled to fit inside the container. I'm using the `contain: "invert"` option to keep the content in view. Despite being described otherwise, this will not keep the content "zoomed to fill" (which is different from "zoom to fit" for different aspect ratios!). Zooming to fill would clip parts of the content that exceed the container's aspect ratio. This is fortunately not the case. In fact I must still set `minScale` to my calculated "zoom to fit" factor to make `contain: "invert"` any useful. (For a clean and meaningful API this should really be done by the library instead.)

The remaining problem is that if the content is smaller than the container in one dimension, the content will be aligned to the bottom/right end in this dimension instead of being centered.

Here are some drawings of the observed situation:
![panzoom-examples2](https://cloud.githubusercontent.com/assets/868315/17139167/974d3382-5343-11e6-84bc-9c21f2226375.png)

What can I do to keep the content centered when possible, instead of having it in the bottom/right corner? Or where in the panzoom library code would that be changed?

**Comment by timmywil** [comment]
This issue looks similar to #148. Centering on zoom can be done with the `focal` option on the `zoom` method. See http://jsbin.com/sojulof/edit?html,js,console,output for an example.

Calculating this automatically can be hairy as there are a lot of factors. I'd prefer to leave this up to the user.

**Comment by ygoe** [comment]
Oh I forgot to mention that I'm exclusively using the mousewheel zooming which already uses the focal point.

Actually, the library already has all the information required to perform these 'contain' checks. I guess it should be easy to apply some more checks and offsets with all the data at hand. From the user perspective, I have nothing at all. Not even the current scale value. No sizes and no positions.

**Comment by timmywil** [comment]
It'd be most helpful to start with an example in code.

**Comment by ygoe** [comment]
Here's an example: https://jsfiddle.net/3pqu4cj6/1/

**Comment by shlomiah** [comment]
Have you tried change contain to: "automatic"?
Example: https://jsfiddle.net/tpadpjbc/

**Comment by ygoe** [comment]
That works well. It somehow wasn't obvious to me from the description. Now I'd just like to keep it centered when it doesn't completely fill the container.

**Comment by SubZero-0** [comment]
I fixed that bug, and published the fix 2 weeks ago or so...  If it can help you I will be very happy 😊

**Comment by timmywil** [comment]
@SubZero-0 Do you have a link to your patch? I don't see a PR.

**Comment by shlomiah** [comment]
https://github.com/timmywil/jquery.panzoom/issues/255#issuecomment-235278279

**Comment by timmywil** [comment]
@shlomiah Your link is broken, but if you're referring to your comment in that issue, some of your code overlaps with the newest version. A PR is much easier to review.

**Comment by timmywil** [comment]
I had a brain fart and stopped dealing with `text-align`. #259 should take care of this issue, combined with the use of `contain: 'automatic'`. Release forthcoming.
