### ISSUE TITLE
contain: true needs to account for margins 

### ISSUE THREAD

**Issue by konnorbeard** [timmywil/jquery.panzoom#259]
### Subject of the issue
Setting "contain: true" in options doesn't contain the panzoom element within its parent. 

### Your environment
jquery.panzoom v3.2.0
jquery v3.1.0
firefox 47.0.1 and chrome 52.0

### Steps to reproduce
https://jsfiddle.net/5pugwy34/4/

### Expected behaviour
The child container shouldn't be able to pan outside of its parent. 

### Actual behaviour
The child container can pan outside of its parent. 

I'll be working on a fix soon because panzoom has been great for my current project...  I can submit a PR when that's done if this issue still exists.

**Comment by konnorbeard** [comment]
Hope that PR helps or at least makes the permanent fix faster to implement.

**Comment by konnorbeard** [comment]
My PR didn't take current zoom level properly into account so I closed it for now.

**Comment by timmywil** [comment]
Thanks for opening an issue. This is a bug due to the recent simplification of containment.

**Comment by konnorbeard** [comment]
This doesn't seem to be fixed - with 3.2.2, same symptoms exist: 

https://jsfiddle.net/5pugwy34/5/

**Comment by timmywil** [comment]
I'm not sure the difference, but I made my own test and it seems work okay. http://jsbin.com/cidebod/edit?html,css,js,output

**Comment by timmywil** [comment]
nvm, there's an issue with confusing parent size with element size.
