### ISSUE TITLE
Zoom out loose focus

### ISSUE THREAD

**Issue by shlomiah** [timmywil/jquery.panzoom#261]
### Subject of the issue
When you zoom in the corner edge and then zoom out the edge - out-borders are seen

### Your environment
* version of jquery.panzoom: 3.1.1
* version of jquery: //code.jquery.com/jquery-git.js
* which browser and its version: Chrome Version 52.0.2743.82 m

### Steps to reproduce
Example: https://jsfiddle.net/tpadpjbc/
1. Do zoom in with mouse scrolling on the text (on the capital C)
2. Do zoom out with mouse scrolling on the text (on the capital C)
(I can do it also with buttons instead of mouse scrolling)

### Expected behaviour
Image will stick to the corner like this:
![image](https://cloud.githubusercontent.com/assets/8141635/17275354/73d5fd94-570d-11e6-823f-452757b80bcd.png)

### Actual behaviour
The image not positioned in the corner, now it looks like that:
![image](https://cloud.githubusercontent.com/assets/8141635/17275349/44471bbc-570d-11e6-8b33-61c0ab357067.png)
There are borders that shouldn't be, If I wasn't clear enough, what I'm trying to say is that the red border and the thin black border should be together and not with space between them.

**Comment by timmywil** [comment]
The flexbox display is really messing with things. You should be able to center without using flexbox. Things should then work as expected.
