### ISSUE TITLE
Touch events not working in multiple browsers

### ISSUE THREAD

**Issue by ygoe** [timmywil/jquery.panzoom#262]
### Subject of the issue
The touch input events for panning and zooming are not working in multiple web browsers.

* Google Chrome 51 and 52 supports panning and zooming
* Mozilla Firefox 47 and 48 supports panning, pinch gesture zooms the entire page as usual
* Microsoft Edge 13 handles all touch events for the entire page as usual

### Your environment
* version of jquery.panzoom 3.1.1
* version of jquery 2.2.3
* which browser and its version (see above)

**Comment by timmywil** [comment]
Thanks for opening an issue. However, touch events are working for me. Please update to the latest jquery.panzoom (currently 3.2.0) and provide a reduced test case using [this template](http://jsbin.com/mofeli/edit?html,js,output) as a base.

**Comment by ygoe** [comment]
Just use your own demo page.

Edge 14 (from Windows 10.1607) still can't do it, it handles all touch events itself and doesn't let panzoom do anything at all. Firefox is unreliable, zooming never works, panning is randomly handled by the browser or by panzoom. Chrome still works correctly.

**Comment by timmywil** [comment]
What device are you using? Do you mean pointer events?

**Comment by ygoe** [comment]
I'm using a Microsoft Surface tablet and a Lenovo Yoga 2 Pro notebook, both with 10-finger touch screen support. And I'm using my physical fingers and put them onto the screen surface and move them. Short: Touch input, not mouse. I'm not familiar with how that's called in JavaScript or how to program it.

**Comment by timmywil** [comment]
Ok, then it's pointer events. I had dropped pointer event support as it was consistently problematic. I had thought that mouse events would still get fired, but it seems I'll need to add them back.

**Comment by timmywil** [comment]
Note: panning will now work again, but I'll need to add pointer gesture support. See https://github.com/timmywil/jquery.panzoom/issues/68 to track that issue. I hope to get to it tomorrow.
