### ISSUE TITLE
Unexpected Rotation Occurring on Zoom

### ISSUE THREAD

**Issue by html5andblog** [timmywil/jquery.panzoom#263]
I'm trying to rotate an image and then allow the zoom and pan effect to be added in the latest version of the plugin with jQuery 3.0.0. When the image is it's default orientation then the zoom works perfectly. Once the image has been rotated though and the zoom happens it's starts rotating unexpectedly on the zoom event.

This seems to be an issue in all the browsers I've tested it in.

I've created an [example of this on CodePen](http://codepen.io/html5andblog/pen/61b49583f601415846eec6625ac94302).

Drag the image first to get it working.

To replicate: rotate the image from it's default orientation and then zoom in and out.

Hope someone can help me out with this. I'm not sure whether it's expected behavior or not.

**Comment by timmywil** [comment]
You're right. I didn't take rotations into account when calculating zoom. I'm not sure the proper formula, but I may be able to rely on the browser when setting.

**Comment by micronaut** [comment]
We are experiencing the same issue when zooming on a rotated image (using version 2.0.6).  Do you know the expected release date of 3.3.0?  Will this also address panning on rotated images?  Currently, when we rotate the image and then try to pan, left-right dragging moves the image up-down and up-down panning moves the image left-right.

Thanks!

**Comment by timmywil** [comment]
> Do you know the expected release date of 3.3.0?

I do this in my off-time, but I'll do my best to make time. Meaning, I'm not sure.

> Will this also address panning on rotated images? 

Yes. It involves using a scale transformation matrix and manipulating matrices, rather than setting indices 0 and 3 on a transform matrix to the desired scale. The latter only works for certain rotations, like the default, but not for all. I've got a pretty good idea of how that will look, but it might take some time.

**Comment by madfriend** [comment]
Hey! @timmywil I appreciate your work and would like to thank your plugin. Is there any hope for a fix to this bug?

**Comment by timmywil** [comment]
@madfriend I will get to this, but I don't know when.

**Comment by tnr2394** [comment]
Any Updates in this issue @timmywil ?

**Comment by jcnventura** [comment]
@tnr2394 Yes. Please test my PR, and provide any comments here, as it may help to get this committed.

**Comment by jcnventura** [comment]
I believe this can now be closed.

**Comment by jtara** [comment]
This broke zoom to specified scale (and, along with that, pinch zoom). see #347.

**Comment by chaodoze** [comment]
This also broke pinch and zoom on iOS
