### ISSUE TITLE
Blurry SVG on zoom for nested SVGs

### ISSUE THREAD

**Issue by markediez** [timmywil/jquery.panzoom#264]
Hello, the SVG is blurry when I zoom in on an svg with nested svg on safari.

```
<svg id="panzoomTarget">
    <svg>...some svg code...</svg>
    <svg>...some svg code...</svg>
</svg>
```

However, it does work well when I do not have nested svgs.

**Comment by timmywil** [comment]
Thanks for opening an issue. This is a browser issue that is too nuanced to address from within the plugin. I believe it has to do with different composite layers. I used to set 'backface-visibility' on the parent, but ended up removing it for this reason. Sorry I can't do more.
