### ISSUE TITLE
Android - Unable to zoom out

### ISSUE THREAD

**Issue by molson504x** [timmywil/jquery.panzoom#265]
### Subject of the issue
On all android browsers, I am able to zoom in on an image, but I cannot zoom out.  I'm not seeing this issue in safari on iOS.  I've tested on multiple devices in multiple versions of Chrome, including latest on Android N.  It's acting almost like it thinks I'm trying to pan instead of zoom after I am zoomed in.

To test this:
1) Create test page with an image in a container, set "panOnlyWhenZoomed" to true
2) Use pinch gesture to zoom in on image.  Note that you can easily zoom in on the image.
3) Try to zoom out, note that you can't zoom out.
4) Disable "panOnlyWhenZoomed" and disable panning on the image
5) Repeat step 2.  Note that you can zoom in on the image
6) Now when you try to zoom out, you'll be able to zoom out.

### Your environment
* version of jquery.panzoom 3.2.0
* version of jquery 1.11.3
* which browser and its version ALL ANDROID BROWSERS

**Comment by timmywil** [comment]
Thanks for opening an issue. However, I don't have a way to test touch gestures on an android device. It seems very odd, though. It's the behavior I would expect if the minScale was set too high. Patch is welcome, as I'm not sure where to go from here.

**Comment by molson504x** [comment]
The minScale is set to 1, maxScale set to 5.  The browser is acting like I'm not pinch-zooming at that point.  I'm not sure if it is a browser issue or if it is a code issue.

I do see this behavior on iOS a little bit, but it seems to resolve itself pretty easily.  I just have to keep trying the pinch zoom motion but eventually on iOS i get it just right to where the phone recognizes that I'm trying to zoom out.

**Comment by molson504x** [comment]
Figured out another part of this.  Turns out, you CAN zoom out on the android devices, as long as you grab the edges of the container instead of the middle of it.  I'm chalking this up to it being a browser issue.  What're your thoughts on that?

**Comment by timmywil** [comment]
Yea, it sounds like a browser issue, but I'll try this out if I can get my hands on a device.

**Comment by cprouvot** [comment]
I have the same problem and in fact i agree with molson504x. You can zoom out when you have a finger in the container and another finger outside the container.

**Comment by molson504x** [comment]
Any updates on this?

**Comment by timmywil** [comment]
@molson504x Do any earlier versions of panzoom work?
