### ISSUE TITLE
Issues with implementing startTransform and zoom pivot

### ISSUE THREAD

**Issue by vhenriques** [timmywil/jquery.panzoom#269]
### Subject of the issue
I have a large image 3456*2304 ,
i need this to be zoomed out when i load the page the first time and i want the zoom pivot to be either at the center of the parent div (when i click zoom-in zoom should occur from center of the div not center of the image) or from top left of parent div .

### Your environment
* version of jquery.panzoom 3.2.1
* version of jquery 1.12
* all modern browsers

### Code 
```
<section id="contain">
    <div class="panzoom-parent" style="height:600px;border: 2px solid #333;overflow: auto; position: relative;">
        <div id="panzoom" style="text-align: top;border: 2px dashed #666;">
            <img class="panzoom" id="storemap_diag" style="z-index: 0;" src="<c:url value=" /resources/images/storemap_diagram.png "/>" alt="Store Map">
            <span title="test01532a004" style="color:#ffffff;background-color:#000000;background-repeat: no-repeat;background-size: 100% 100%;font-weight:bold;line-height:50px; z-index: 1;position: absolute; left:1065.3661041676799px; top:1076.7723775713662px">1700</span>
            <span title="test01532a008" style="color:#ffffff;background-color:#000000;background-repeat: no-repeat;background-size: 100% 100%;font-weight:bold;line-height:50px; z-index: 1;position: absolute; left:1455.4987501823664px; top:1364.618314448281px">1710</span>
        </div>
    </div>
</section>
```

```
 $("#panzoom").panzoom({
			  $zoomIn: $("#zoom-in"),
			  $zoomOut: $("#zoom-out"),			  
			  $reset: $("#reset")
			});
		
		 $("#panzoom").panzoom("option", {
			   increment: 0.5,
			   startTransform: 'scale(0.35)',
			   focal: {clientX:0, clientY:0},
			   minScale: 0.25,
			   animate: true,
			   maxScale: 2,
			   duration: 500
			 });
		
```

So for the first part where i wanted my initial loaded zoomed out image [ startTransform: 'scale(0.35)', ] aligned top left i went ahead and changed

'transform-origin': this.isSVG ? '0 0' : '50% 50%'
to
'transform-origin': this.isSVG ? '0 0' : '0 0'
 in panzoom.js
it sets my image as follows (aligned top and left)
![capture](https://cloud.githubusercontent.com/assets/3635834/17965165/c8730f34-6ad8-11e6-832d-e2d9b7d5c491.PNG)

but a zoom out with a increment of 0.5 results in such a scenario,
![capture](https://cloud.githubusercontent.com/assets/3635834/17965199/f48e374c-6ad8-11e6-9099-990b14f571ef.PNG)
im thinking focal: {clientX:0, clientY:0}, sets the zoom pivot and zoom will lock  on set x y and zoom.
Im trying to get zoom to zoom from top left or center of image shown in container.

Any pointers as to what values i should set for setting the zoom pivot?

Thanks in advance for your help
and releasing this great library .
Cheers

**Comment by timmywil** [comment]
Modifying the `transform-origin` will cause some wacky behavior associated with focal point zooming. But, note that `focal` is not an option to pass to panzoom. It is only an option on the `zoom` method. However, it sounds like you may not need the focal option, and overriding `transform-origin` may just give the behavior you want without setting focal.

See http://jsbin.com/fevolun/1/edit?html,js,output as an example.

**Comment by vhenriques** [comment]
hi
thanks i was able to get image to zoom from top left
can you tell me what will the values be to make the image zoom from center of the current image in view?
thanks
