### ISSUE TITLE
Zooming on mobile

### ISSUE THREAD

**Issue by ActiveScottShaw** [timmywil/jquery.panzoom#270]
We have both '**pan and zoom**' enabled which works great a PC.

When trying it on a mobile device (tested on android phone and iOS tablet), the pan is fine .... but when trying to do the **pinch zoom** it does not work ... it seems to trigger the pan first. 

If you turn off pan, then the pinch zoom works as expected.

Has anyone else come across this before?

**Comment by godavem** [comment]
I'm also finding that the **pan vs. zoom sensitivity** is very skewed toward panning on an iPhone 5 (Safari). If I'm very precise I can get it to zoom, but generally it wants to pan. I would love to know if there's a way to adjust this, because right now it's unusable from my purposes.

**Comment by Risingson** [comment]
Something broke, was working well in 3.2.0

**Comment by timmywil** [comment]
Thanks for opening an issue. Please create a test case (with any Panzoom options you're using) to help assess the issue. You can start with [this template](http://jsbin.com/mofeli/edit?html,js,output). 3.2.1 added back Pointer Event support, which may have something to do with the behavior in Android, but I cannot reproduce the behavior in iOS. Versions of Android and iOS would also be helpful.

**Comment by timmywil** [comment]
Actually, I looked at this on iOS again and was able to reproduce the issue. I think I've fixed it, but please have a look in Android with the latest version as I don't have a way to test a physical Android device.

**Comment by molson504x** [comment]
This feels similar to the issue I posted a couple of weeks ago, where the library skews heavily towards panning vs zooming.  I'm going to import the latest released version and test with that.

**Comment by molson504x** [comment]
@timmywil The latest release seems to have fixed the issues I was having as well.

Thanks!

**Comment by ActiveScottShaw** [comment]
Thanks @timmywil that seemed to do the trick! :)
