### ISSUE TITLE
Return to start postion as you zoom out 

### ISSUE THREAD

**Issue by mab3103** [timmywil/jquery.panzoom#272]
As I zoom out of the image I want to it to return to it's starting position. Is there a way to this that you know of? Something like forcing the image to transtion towards the centre as you zoom out but I am unsure of how to do this.

Any ideas would be great!

**Comment by timmywil** [comment]
Thanks for opening an issue. You should be able to accomplish this with the `resetPan` method. See http://jsbin.com/kileta/edit?js,output.
