### ISSUE TITLE
Basic panzoom use case, but having an issue making sense of the results

### ISSUE THREAD

**Issue by kgraves** [timmywil/jquery.panzoom#273]
First off just wanted to thanks the contributors and author for this, it's a great tool, and I'm glad it exists! :+1: 

### Subject of the issue
I've setup a [jsfiddle](https://jsfiddle.net/kgraves/pjxwLtm8/) to demonstrate my issue.

I'm building a system where I have data like the following:

```javascript
[
  {
    x: 200,
    y: 200,
    zoomFactor: 1.2
  },
  ...
]
```

Based on certain user input, I need to pan and zoom the image to the above defined points. (pretty basic) However, I'm having some weird behavior that I'm not entirely understanding.

The pan and zoom features of the library seem to affect each other in odd ways. I'll describe in detail in the "Steps to reproduce" section. This is issue makes me feel like I'm missing something big about this library, but I don't see anyone talking about the issue I'm having nor any example to account for this.

Any pointers, advice, or examples are much appreciated!

### My environment
* jquery == 3.1.0
* jquery.panzoom == 3.2.2
* chrome == 52.0.2743.116
* ubuntu == 16.04

### Steps to reproduce
1) open the above jsfiddle
2) open dev tools for info logged to the console
3) click the 'Details' button in the demo
4) notice that the position of the image is logged to the console. Currently it's at (0, 0).
5) click the 'Pan' button, then again click the 'Details' button
6) notice that the image was moved to (200, 200), where we want it.
7) now click the 'Zoom' button, and again click the details button
8) notice that the image has moved from (200, 200) and is now at (208, 244)
**NOTE** This same issue happens when zooming first, then panning, although the coordinates differ.

### Expected behaviour
I naively expect that the image will be zoomed to the given zoomFactor AND the image should stay where I've panned it to, namely (200, 200).

### Actual behaviour
When zooming the image pans away from the previously set coordinates

**Comment by kgraves** [comment]
I've been playing with this for the past few days, and am going through the source to try to debug further, or at least understand the results.

I've also found that the problem is exacerbated when the zoom factor is higher. So for instance, in the above jsfiddle, when the zoom factor is 5, and you first zoom, then pan, I would expect the image to be at `(200, 200)` since the last operation was panning. However, the image ends up at (-1346, -1000)... wat


Has anyone else experienced this behavior, or have any advice on how to mitigate/solve this issue?

**Comment by timmywil** [comment]
It looks like you're using focal point zooming, which uses a complicated formula to zoom in on a particular point. The resulting coordinates depend on a lot of things, including the focal point, zoom factor, parent offset, and others. Have a look at the [demo page](http://timmywil.github.io/jquery.panzoom/demo/#focal) for an example of how focal point zooming can be used effectively.

**Comment by timmywil** [comment]
By the way, you can set the pan coordinates separately from the zoom if you want to keep certain x/y coordinates: https://jsfiddle.net/timmywil/oc4xju5q/

**Comment by kgraves** [comment]
I started using focal point zooming, because I wanted to zoom respective to a particular point. In my example, I started using the upper left corner to see if that would stay stationary.

I think I may have not explained my problem well. I've definitely taken a look at the demo page many times, but haven't seen examples there, or elsewhere, like what I'm trying to achieve. All the examples I've seen rely on human input to pan and zoom, and are not trying to get the image placed precisely. I'm looking to pan and zoom programmatically. Given an (x,y) pair and a (width, height) (which I convert to a zoom factor) of a specific section of an image, I want to move said image to make that section front and center.

Here is a very crude example:

```text
+------------------------------------------+
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|
|
|
|
|
|
```

**Comment by kgraves** [comment]
I think I may have not explained my problem well. I've definitely taken a look at the demo page many times, but haven't seen examples there, or elsewhere, like what I'm trying to achieve. All the examples I've seen rely on human input to pan and zoom, and are not trying to get the image placed precisely via data. I'm looking to pan and zoom programmatically, via your API. Given a predefined set of data: an (x,y) pair and a (width, height) (which I convert to a zoom factor) of a specific section of an image, I want to move and zoom the image to the section defined in the data.

The thing I'm misunderstanding the most is the API that I'm given. For `pan` I'm supposed to specify an (x,y) pair in pixels. However, if I do anything other than panning, for instance a call to `zoom`, quickly invalidates those (x,y) coordinates. They no longer represent the correct point on the image.

I may be wrong here, but does the library not account for this change in zoom when the `pan` method is called? The example you wrote above demonstrates this exactly:

```javascript
$('.panzoom')
    .panzoom('zoom', 2)
    .panzoom('pan', 200, 200);
```

I read it as: zoom with a factor of 2, then move the image to (200,200) pixels. However, what I see happen is that the image moves up and to the left, in the **negative** direction. Precisely, it was moved to (-186.5, -100). These coordinates do not seem to represent (200,200) respective to the parent container, nor the origin of the parent container. They don't seem the represent the coordinates when taking the zoom factor into account, which might be something like (400, 400) for a zoom factor of 2.

**Comment by kgraves** [comment]
Ah, there we go. The first example in your above comment does the trick.

```css
.panzoom {
  ...
  transform-origin: 0 0 !important;
}
```

I tried doing that, but forgot to set the `!important` on it, so it probably got overridden shortly thereafter.

Thanks for your help @timmywil, I really appreciate it!
