### ISSUE TITLE
Add support double tap zooming

### ISSUE THREAD

**Issue by ThorConzales** [timmywil/jquery.panzoom#275]
Hi,

Please consider adding support for double tap zooming. I guess the feature should work in toggle mode. When double tap occurred it then either zooms in to max level or zooms out to min level depending in which zoom level it currently is. Maybe add some configuration options which zooming options are used.

It would be also nice if it additionally has the same feature as Android has which is when you double tap but don't release the finger from the second tap then you can select the zoom level only with one finger by either moving away your finger from the initial double tap location to zoom in and when you move the finger closer to initial double tap location then it zooms back out.

If you don't want to add tapping feature then please advice how I can listen to tap/click events without interfering the library events so I could add the support programmatically myself.

**Comment by timmywil** [comment]
Thanks for opening an issue. [hammer.js](http://hammerjs.github.io/) is a good option for handling different kinds of touch gestures, then just call the panzoom `zoom` method.

**Comment by ThorConzales** [comment]
Thanks for the hint, works like a charm. Here is the sample code should anyone else like to add double tap support:
       ```
$("#container").panzoom({
            minScale: 0.5,
            maxScale: 1.5
        });

        $("#container").on('panzoomzoom', function (e, panzoom, scale) {
            currentZoomScale = scale;
        });

        var mc = new Hammer.Manager(document.getElementById('container'));
        mc.add(new Hammer.Tap({ event: 'doubletap', taps: 2 }));

        mc.on('doubletap', function (ev) {
            var zoom = 1.5;
            if (currentZoomScale > 1) {
                zoom = 0.5;
            }
            $("#container").panzoom("zoom", zoom, {
                animate: true,
                focal: {
                    clientX: ev.center.x,
                    clientY: ev.center.y
                }
            });
        });
```
