### ISSUE TITLE
Pan and clickable elements - Devices

### ISSUE THREAD

**Issue by ScottShaw** [timmywil/jquery.panzoom#277]
We have noticed that if you have 'Panning' turned on .... and you have clickable elements ... these elements become un-clickable on Mobiles and Tablets .... both apple and android.

We have added in the 'stopImmediateProagation' stuff .... but still does not work.

It seems to trigger the 'pan' event' even when you click

All works if you turn panning off.

Any ideas?

We are using the latest panzoom version : 	3.2.2

**Comment by ScottShaw** [comment]
FYI - The demo you have put together for 'clickable' links in codepen, does not work on mobile devices either.

http://codepen.io/timmywil/pen/lpIaG

**Comment by timmywil** [comment]
@ScottShaw I obviously did that demo, but I'm not sure where you found it. This is the demo I put together for this issue from the README: http://codepen.io/timmywil/pen/bFiqy. It works for me on iPhone. `.stopImmediatePropagation` prevents the panzoom handler from being called.

**Comment by ScottShaw** [comment]
Try the demo i linked to ... which has 'PANNING' ... that doenst work on devices.

The one you linked to DOES work .... but it has not got 'panning'

.stopImmediatePropagation doesnt seem to make a difference when you have panning turned on (already tried this :)   )


Ps. Demo came up in a google search

**Comment by ScottShaw** [comment]
ok, so your demo does work ..... but you only have 'panning' once you zoom in .... The other demo, and how we are doing it, has 'panning' turned on all the time (not just when you are zoomed in) ... and it does not work on your demo or on ours in that scenario

So ... could it be some sort of issue if 'panning' is on from the 'start'?

**Comment by timmywil** [comment]
That particular demo uses the contain option. So, panning is always on, but it's not allowing movement until it's zoomed. We could probably troubleshoot better if you create a test case to hack on together.

**Comment by ScottShaw** [comment]
Hi, we have forked your pen and adjusted it slightly to how we currently have it. This works on desktop, but not on devices (ipad,iphone,android).

We dynamically add content into the panzoom area of the page, so those links need to be clickable as well .... but with the 'function' how we have it nothing works on devices 

Doing the function the way you suggested works, but not for newly added elements

Any ideas?

http://codepen.io/ActiveAdam33/pen/ORbvQP

**Comment by timmywil** [comment]
@ScottShaw This seems to work: http://codepen.io/timmywil/pen/EgNBRE . You might need to attach event delegation rooted at the panzoom element so the `stopImmediatePropagation` applies to the right handlers. This has the added advantage of being a little faster than delegating all the way up to the body.

**Comment by ScottShaw** [comment]
Thanks for your demo, it really helped a lot .... we have rejigged according to your demo and got it to work.

Had some 'fun' with bootstrap stuff not playing ball though :)

Thanks again for taking the time to help!
