### ISSUE TITLE
Possibly an enhancement request - non-zoomed child elements

### ISSUE THREAD

**Issue by nhall** [timmywil/jquery.panzoom#280]
### Non-zoomed child elements

This plugin is excellent.  I plan to use it to allow for panning and zooming of a map. The issue I have is that I am plotting points on the map with labels. I can position them with percentages so they are displayed in the correct location.  However, the size of the points and the labels scale with image since the parent is transformed. Is there anyway to whitelist these points so they are not transformed? Or perhaps transform the inverse?  Thanks.

**Comment by Risingson** [comment]
Not sure what your technical setup is there, but you would bind a container (including some marker and label) to a coordinate on your map. When zooming you would use the onZoom panzoom event to scale your container relative to the zoom level.

**Comment by timmywil** [comment]
Thanks for opening an issue. Unfortunately, this is the nature of CSS. There are a couple options:

1. Scale all the other elements, excluding the one you don't want to scale, but this won't scale the container.
2. Scale the container and re-scale the element you don't want to scale. However, that can sometimes result in the child elements looking blurry.
