### ISSUE TITLE
Weird problem while using setMatrix

### ISSUE THREAD

**Issue by aetherwu** [timmywil/jquery.panzoom#289]
Here's what I did in console step by step:

//print 
matrix_string
//"["2.1844094061599195","0","0","2.1844094061599195","170.2000906918778","-9.815817022003813"]"

//now try to pass to setMatrix since setMatrix accept String
$("#headimg").panzoom('setMatrix', matrix_string)
//[1, 0, 0, 1, 0, 3.53125]
//I failed.

//OK, let me pass a json to setMatrix
$("#headimg").panzoom('setMatrix', JSON.parse(matrix_string))
//["2.1844094061599195", "0", "0", "2.1844094061599195", 0, 3.53125]
//first 4 numbers works

//Let me do it again right after last step
$("#headimg").panzoom('setMatrix', JSON.parse(matrix_string))
//["2.1844094061599195", "0", "0", "2.1844094061599195", 170.2000906918778, -9.815817022003813]
//why does it work at this time....

**Comment by aetherwu** [comment]
So I've got a workaround!

`$("#headimg").panzoom("setMatrix", JSON.parse(matrix_string))
`$("#headimg").panzoom("setMatrix", JSON.parse(matrix_string))

I repeat these two statement and I've got what I want!
But WHY T_T|||

**Comment by Risingson** [comment]
"[2.1844094061599195,0,0,2.1844094061599195,170.2000906918778,-9.815817022003813]" ?

**Comment by aetherwu** [comment]
@Risingson it was extracted by 'getMatrix' from anther panzoom object.

**Comment by Risingson** [comment]
sorry i meant if you tried without all those apostrophes ?

**Comment by timmywil** [comment]
Thanks for opening an issue, but `setMatrix` expects an array. https://github.com/timmywil/jquery.panzoom/#setmatrix-matrix-options-
