### ISSUE TITLE
Transform property can't be reset nor set from JS

### ISSUE THREAD

**Issue by jdreg95** [timmywil/jquery.panzoom#291]
Hi,

I've been trying to use this plugin to set-up a pinch to zoom + panning image in a mobile image gallery. Zooming and panning works fine, though I would want to reset the image to it's original transform data when I reach the minimum scale.

I have tried:

- Manually resetting the transform property by writing code for it
- Using all the set and/or reset methods

Neither work, though, when setting a different CSS property, like `display: none;`, the panzoom image does get updated when it reaches the minimum scale, disappearing.

Why could it be that I can't set or reset the transform property?

Here is my code:

```
that = @

    $('.panzoom').each((k, v) ->
      elHammer = new Hammer(v)
      elHammer.get('pinch').set({ enable: true });

      elHammer.on('pinchmove', (e) =>
        $(v).panzoom({
          minScale: that.opts.scaleMin,
          maxScale: that.opts.scaleMax,
          animate: false,
          increment: 0.1,
          focal: {
            clientX: e.center.x,
            clientY: e.center.y
          }
        }).on('panzoomzoom', (pe, panzoom) =>
          if panzoom.scale == that.opts.scaleMin
            # Reset here
        )
      )
    )
```

**Comment by timmywil** [comment]
Thanks for opening an issue. However, I'll need a test case to properly help. Will reopen if this is a bug.
