### ISSUE TITLE
Nested panzoom containment and scale issues

### ISSUE THREAD

**Issue by telekovar** [timmywil/jquery.panzoom#292]
When nesting, things get a little strange. After zooming on the parent panzoom, the children panzooms have their panning either scaled up or down in speed.

When contain on the children is set, it incorrectly calculates the bounds of the parent, either zoomed or not.

Am I using this incorrectly, or do you think this is a bug?

Here's a gist.
[https://gist.github.com/telekovar/696202871c255c96179a47ceaeaf9133](https://gist.github.com/telekovar/696202871c255c96179a47ceaeaf9133)

**Comment by ciao-chung** [comment]
Hi, did you find any solution for this issue?
