### ISSUE TITLE
panzoom for dynamically added content

### ISSUE THREAD

**Issue by leenthegenieass** [timmywil/jquery.panzoom#293]
panzoom doesnt seem to be working with dynamically added content. Is there is a way to refresh panzoom with body.on(change) ?

**Comment by timmywil** [comment]
The change event doesn't work that way. If you really need to watch for DOM changes, you could use [Mutation Observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). However, if you are the one adding the content, you'll just need to call panzoom on the new elements.
