### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

### ISSUE THREAD

**Issue by romy2012** [timmywil/jquery.panzoom#295]
```
var $section = $('.m-topic');
var $panzoom = $section.find('.pan-zoom').panzoom({
	$zoomIn: $(".zoom-in"),
	$zoomOut: $(".zoom-out"),
	$reset: $(".zoom-reset"),
	minScale: 1,
	maxScale: 5,
	contain: 'invert'
}).panzoom('zoom', true);
```

erro in chrome,  how to  solve?

Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by timmywil** [comment]
Thank you for opening an issue, but I'm not sure the problem. Will reopen with a test case.

**Comment by brunoalano** [comment]
Same error

**Comment by brunoalano** [comment]
Fix:

```javascript
    $('.flowchart').find('div').on('pointerdown mousedown touchstart', function(e) {
      e.stopImmediatePropagation();
    });
```

The `pointerdown` event that fixed for me.

**Comment by deepak-ui** [comment]
Unable to preventDefault inside passive event listener due to target being treated as passive. navigation is not working

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  You should be able to fix this by adding an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).  That's always been necessary if you're going to use pointer events.
