### ISSUE TITLE
Dynamic rotation

### ISSUE THREAD

**Issue by SpicerSolutions** [timmywil/jquery.panzoom#296]
### Subject of the issue
Is it possible to dynamically change to rotation of the image?

I've tried setting the setTranform method to the rotation

.panzoom('setTransform','rotate(270deg)');

This does rotate the item but then changing the zoom either resets the rotation or starts to rotate the item back towards 0deg.

**Comment by timmywil** [comment]
This is not yet possible. Please follow #263.
