### ISSUE TITLE
Gap above image, and unable to see the bottom of it

### ISSUE THREAD

**Issue by mikebabb-gc** [timmywil/jquery.panzoom#313]
### Subject of the issue
When panning or zooming the image, it is possible to drag the image down to reveal a gap between the top of the image and its parent element. From the documentation, I thought `contain: 'invert'` would prevent this.

I'm also not able to see the bottom of the image when panning it the other way.

### Your environment
* version of jquery.panzoom: **3.2.2**
* version of jquery: **3.1.1**
* which browser and its version: **Chrome 55.0.2883.87**

### Steps to reproduce
See reduced test case at https://codepen.io/mikegbabb/pen/53d071b6b8e96749135f2f089436b943/

### Expected behaviour
To be able to pan and zoom the image (which I can), but without the image being pulled far enough in any direction to reveal the background of the parent (see codepen above)

### Actual behaviour
By panning the image down, the a gap between image and parent element is revealed. In the test case codepen above, this is demonstrated when the blue background of the parent element is visible.

**Comment by mikebabb-gc** [comment]
This might not be a plugin issue, but having spent a while going through the documentation and Googling the problem, I've been unable to see what I'm doing wrong.

**Comment by Spooner** [comment]
I have an identical problem.

**Comment by Spooner** [comment]
This is a duplicate of #306.

**Comment by mikebabb-gc** [comment]
@Spooner Thank you very much for your fix! Reverting to version 2.0.5 of the plugin as you suggest does indeed resolve the issue. As yours is still open, I'll close one.

Thanks again!
