### ISSUE TITLE
Hi, i'm glad for meet you. Could i ask you?

### ISSUE THREAD

**Issue by kkotkkio** [timmywil/jquery.panzoom#318]
### 
I want to move image with mouseover and move, no click, 
just when mouse over on image and mousemove, is moved.

First, I'm sorry that i'm not well english.

I want to use panzoom like this.
https://www.everlane.com/products/womens-modern-loafer-burgundy?collection=womens-shoes

Everlane site's image is zoomed when you click the (+) button.
And when mouseover on image, start ready for move. 
And mousemove on image, is moved image.

How to available in jquery.panzoom?

### My environment
* version of jquery.panzoom : v3.2.2
* version of jquery 1.11.2
* which browser and its version : Chrome latest

**Comment by jcnventura** [comment]
Panzoom doesn't automatically pan with mouse movements.
