### ISSUE TITLE
Panning don't work on Chrome

### ISSUE THREAD

**Issue by rpallares** [timmywil/jquery.panzoom#320]
### Subject of the issue
Panning don't work on latest chrome version. On click zoom is set to minimum and panning is set to 0,0.
Into HTML the "transform: matrix" hint disappear.

### Your environment
* version of jquery.panzoom: 3.2.2
* version of jquery: 1.11.0 (sorry for that)
* which browser and its version: Chrome 56

### Expected behaviour
Panning should working well (perfect into Firefox)

### Actual behaviour
Transformation matrix disappear from HTML, zoom is set to minimum and panning go to top left corner

**Comment by rpallares** [comment]
Hi,

I don't know if the issue really should be fixed, I know my JQuery version may be responsible.
But the fix is very easy, it just require to use the originalEvent object:

Lines 1204 and 1205:
```
startPageX = event.originalEvent.pageX;
startPageY = event.originalEvent.pageY;
```


Lines 1246 to 1250:
```
self.pan(
	origPageX + coords.originalEvent.pageX - startPageX,
	origPageY + coords.originalEvent.pageY - startPageY,
	panOptions
);
```

**Comment by jfunchion** [comment]
@rpallares 

I seem to be having the a similar problem where the panning does not working in Chrome 55 and 56.  It works fine in FF.  I'm trying to use your solution, but I'm pretty new to coding.  How exactly did you add that code into panzoom 3.2.2.  Here's lines 1200 to 1257 in my file.  Thank you so much for your help.


`var move = function(e) {
				var coords;
				e.preventDefault();
				touches = e.touches || e.originalEvent.touches;
				setStart(e, touches);

				if (touches) {
					if (touches.length === 2) {

						// Calculate move on middle point
						var middle = self._getMiddle(touches);
						var diff = self._getDistance(touches) - startDistance;

						// Set zoom
						self.zoom(diff * (options.increment / 100) + startScale, {
							focal: middle,
							matrix: matrix,
							animate: 'skip'
						});

						// Set pan
						self.pan(
							+matrix[4] + middle.clientX - startMiddle.clientX,
							+matrix[5] + middle.clientY - startMiddle.clientY,
							panOptions
						);
						startMiddle = middle;
						return;
					}
					coords = touches[0] || { pageX: 0, pageY: 0 };
				}

				if (!coords) {
					coords = e;
				}

				self.pan(
					origPageX + coords.pageX - startPageX,
					origPageY + coords.pageY - startPageY,
					panOptions
				);
			};

			// Bind the handlers
			$(document)
				.off(ns)
				.on(moveEvent, move)
				.on(endEvent, function(e) {
					e.preventDefault();
					// Unbind all document events
					$(this).off(ns);
					self.panning = false;
					// Trigger our end event
					// Simply set the type to "panzoomend" to pass through all end properties
					// jQuery's `not` is used here to compare Array equality
					e.type = 'panzoomend';
					self._trigger(e, matrix, !matrixEquals(matrix, original));
				});`

**Comment by paramir** [comment]
I was experiencing the same issue, same jQuery version. changing to a newer version of jQuery does seems to solve the issue. your fix does solve the issue if you need to stay on 1.11.

**Comment by rpallares** [comment]
Hi,

Yes it's possible. I was obliged to stay in that JQuery version.

Thx
