### ISSUE TITLE
Is not a problem, but a question for my project!

### ISSUE THREAD

**Issue by rafaeldcastro** [timmywil/jquery.panzoom#329]
### Subject of the issue
I have an element that works perfectly, pan, zoom, etc :D
But I would like to know if there is a possibility as soon as you finish the necessary adjustments(pan, zoom), I be able to pick up the coordinates of the element and with a button pass to another element on the page?

I saw the getTransform and setTransform, but with no examples couldn't figure it out.

Yes, I'm new and noob. Thanks for the excellent plugin by the way!!

### Your environment
* version 3.2.2
* version of jquery 3.1.1
* Chrome 57.0.2987.133 (64-bit)

### Expected behaviour
Pan, zoom an element. Click a button and apply those adjusts to an another element on the page.

### Actual behaviour
I don't know how to do....or if its possible to do.

**Comment by shlomiah** [comment]
I did something like this:
`var matrix = dz.getMatrix();
if (!matrix) return;
var $dest = $element.find('.img');
var scale = +matrix[0];
    		if (scale === 1) {
    			$dest.css('transform', 'matrix(1, 0, 0, 1, 0, 0)');
    			return;
    		}
var destWidth = $dest.parent().width();
var destHeight = $dest.parent().height();
var axisX = +matrix[4];
var axisY = +matrix[5];
var $src = $('.player');
var srcWidth = $src.width();
var srcHeight = $src.height();

var axisRatioX = axisX * 2 / (srcWidth * (scale - 1));
var axisRatioY = axisY * 2 / (srcHeight * (scale - 1));
matrix[4] = axisRatioX * (destWidth / 2) * (scale - 1);
matrix[5] = axisRatioY * (destHeight / 2) * (scale - 1);
var transform = 'matrix(' + matrix.join(',') + ')';
$dest.css('transform', transform);
`
I trigger this code every time the src zoom\pan is happen, and its updating the dest accordingly
