### ISSUE TITLE
This plugin is not working after upgrading Chrome to v59

### ISSUE THREAD

**Issue by tom10271** [timmywil/jquery.panzoom#340]
### Subject of the issue
http://timmywil.github.io/jquery.panzoom/demo/

It was working fine in the past but not now in Chrome v59

### Your environment
* 3.2.2
* v3.1.0
* Chrome 59

### Steps to reproduce
For Panning and zooming with CSS3, you can zoom in and pan but you cannot zoom out

### Expected behaviour
For Panning and zooming with CSS3, you can zoom in and pan. I should also be able to zoom out

### Actual behaviour
For Panning and zooming with CSS3, you can zoom in and pan but you cannot zoom out

**Comment by tom10271** [comment]
I guess this project is dead....

**Comment by timmywil** [comment]
@tom10271 Not dead, but work on this is done in our off-time. Hopefully we'll be able to address more issues soon.
