### ISSUE TITLE
Jquery click events not firing

### ISSUE THREAD

**Issue by rasovica** [timmywil/jquery.panzoom#344]
I define a click event hendler like so for a svg
`$('path').on('click', function() {alert("clicked)}`
But after
`    $("#map").panzoom({
        minScale: 1,
        maxScale: 4,
        contain: true
    });`
The events stop firing (map is the container div for svg (svg has paths which i want to be able to click and zoom into))
I should mention that i am using jquery 1.12.4 in case you think thats the problem

**Comment by timmywil** [comment]
I believe question #2 of the FAQ will solve this issue. https://github.com/timmywil/jquery.panzoom#faq
