### ISSUE TITLE
Sync Pan/Zoom across multiple images

### ISSUE THREAD

**Issue by OmniCHI** [timmywil/jquery.panzoom#350]
### Subject of the issue
Attempting to get panzoom to sync across multiple images

### Your environment
* version of jquery.panzoom: 3.2.2
* version of jquery: 3.2.1
* which browser and its version: Firefox 54.0.1

I am using the getMatrix and setMatrix methods to update multiple panzoom images at once, however I can not get more than one additional image to update at once. If I want three images to all zoom and pan in sync only two of them will do so.

**Comment by omnitographer** [comment]
Nevermind, figured out what I was doing wrong. For anyone wanting to update multiple images at once this was what I did, I fed the value of getMatrix into setMatrix during an onPan event for each of my images, worked like a charm.
