### ISSUE TITLE
作者您好，3.2.2版本有点问题，手机上放大手势不生效

### ISSUE THREAD

**Issue by sxsnwangrenfei** [timmywil/jquery.panzoom#371]
### Subject of the issue
Describe your issue here.

### Your environment
* version of jquery.panzoom
* version of jquery
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](http://jsbin.com/mofeli/edit?html,js,output) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by jcnventura** [comment]
Sorry. empty issue.
