### ISSUE TITLE
Zoom-in is blurry in webkit-based browsers

### ISSUE THREAD

**Issue by adred** [timmywil/jquery.panzoom#84]
I think the title explains itself. In Firefox and IE, the issue doesn't occur.

**Comment by jdonahue82** [comment]
I am working on a related problem where the initial rendering of a downscaled image gets extremely pixelated when panzoom is enabled. This does not occur in Firefox, but does occur in Chrome and IE. When applying the suggestion from @gius80 it renders correctly in Chrome. Still testing IE and failing at least in IE9. Thanks for bringing me one step closer!

**Comment by marcelboettcher** [comment]
@jdonahue82 does it work for you in Safari as well? No solutions works in Safari for me.

**Comment by sgrgala** [comment]
@marcelboettcher I agree. None of the solutions are working for Safari

**Comment by redaxmedia** [comment]
According to my experience with a custom zoom (not jquery.panzoom) implementation:

Mobile Safari and Chrome get blurry once you have multiple elements using CSS transform laying over another using CSS position.

I guess this is a gernal issue with multiple layers that get hardware accelerated.

Maby this is helpful for solving the problem.

**Comment by tuckerconnelly** [comment]
Found another workaround!

You can force a redraw on panzoomzoom using [link to this](http://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes) code.

This is the same as backface-visibility: initial, though, super slow. So you can debounce the function by 100ms. I used lodash for this, but you can manually debounce.

Here's the code:

```javascript
$('#plane').on('panzoomzoom', _.debounce( function () {
	this.style.display='none';
	this.offsetHeight;
	this.style.display='';
}, 100));
```

Hope this helps :)
